### ISSUE TITLE
Co-working session #1

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#1]
Bring your latest coding project to this [co-working session](http://mozillascience.github.io/studyGroupHandbook/events.html) - hang out with peers, share tips, ask questions, and show off your work! Beginners are welcome, and all questions are good questions. 

Feel free to come for all or part of this session. At the beginning, we'll go around and give everyone a chance to quickly describe what they're working on and what tools they're using. 

**When**: Thursday, June 25, 2015, 5:30 pm - 7:30 pm
**Where**: MP 408 (Mclennan Physical Labs, in the Burton tower)
**What to bring**: Computer and any materials you want or need for your work.

**Comment by ekzhu** [comment]
I will be working on Python parallel (multi-process) programming.

**Comment by SDominique** [comment]
I'll bring some cookies!

**Comment by QuLogic** [comment]
Something came up, but if you need me, I'll be in gitter.
