### ISSUE TITLE
Unit testing in Python

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#10]
@aerler will be introducing the concept of unit tests through some Python examples. The lesson is aimed at people with no unit testing experience. 

**When: August 27, 2015, 6:00 pm - 7:00 pm**
**Where: [McLennan Physics building](https://www.google.ca/maps?q=mclennan+physical+laboratories&ion=1&espv=2&bav=on.2,or.r_cp.&bvm=bv.99261572,d.aWw&biw=1517&bih=714&um=1&ie=UTF-8&sa=X&ved=0CAYQ_AUoAWoVChMIjsSwkuePxwIVxDqSCh0SbwDk) Rm. 408**
**Preparation:** Bring a computer with a working version of [Python](https://www.python.org/)

**Directions to MP408:**
Room 408 is in the Burton Tower, 4th floor.
From St. George Street: go in the main doors and turn left, then right (through three sets of doors) until you hit the elevators. 
From Huron Street: go in the doors and turn right, then right again (through three sets of doors) until you hit the elevators. 
From Russell Street: go in the doors and turn left (one set of doors), you'll be right at the elevators.

**Comment by mbonsma** [comment]
Just a reminder that unit testing in Python is happening tonight at 6!

**Comment by QuLogic** [comment]
@aerler Please remember to post your lesson at some point.

**Comment by aerler** [comment]
I'll do it tomorrow. I've been a bit lazy after submitting my thesis... and I have some things to do today.
