### ISSUE TITLE
Intro to Bash - May 31

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#101]
Learn basic command line in Bash and shell scripting. 

**Where**: MP408
**When**: Wednesday, May 31st, 6:10pm
**Instructor**: @joelostblom 
**What to bring**: If you're using OSX or Linux systems, you will be able to follow along in a regular terminal. 
If you are using Windows, we often use Git Bash which comes with an [installation of Git](https://git-scm.com/downloads).

**Comment by joelostblom** [comment]
If you're on windows, also install the [software carpentry version of the text editor `nano`](https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe), after you have installed git-bash.

**Comment by mbonsma** [comment]
The video got cut off a few times, but here's most of it! https://www.youtube.com/watch?v=-1E61HswswU
