### ISSUE TITLE
Python: scikit-learn for Machine Learning - June 7

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#102]
Get an overview of how to use Python's scikit-learn package to implement common machine learning algorithms for problems like regression, and classification.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday, June 7th, 6:10-7pm
**Instructor**: Nil Sahin
**What to bring**: 
- We highly suggest using the Anaconda distribution of Python ([setup instructions here](https://uoftcoders.github.io/studyGroup/lessons/r-python-conda-setup/)) which will have all the scikit-learn package dependancies. 
- Next, install [scikit-learn](http://scikit-learn.org/stable/install.html) using `pip install -U scikit-learn` or `conda install scikit-learn`

**Comment by jdpigeon** [comment]
Oooo nice!

Might I suggest we touch briefly on [TPOT](https://rhiever.github.io/tpot/)?

**Comment by linamnt** [comment]
@jdpigeon the lesson will feature a short [TPOT](https://rhiever.github.io/tpot/) demo :)

**Comment by linamnt** [comment]
The lesson content is available here: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/scikit-learn/UofTCoders_ML.ipynb
If you'd like to run it during the lesson, save the raw contents into a a file ending .ipynb and it should be able to run as a Jupyter notebook.

**Comment by QuLogic** [comment]
Live video stream is [here](https://youtu.be/UhwY_4-qHUo).
