### ISSUE TITLE
Coworking Session - Pair Programming on Unit Testing - June 14

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#103]
Are you interested in starting to include testing of your code? It's a really great way to ensure your code is robust to new changes and working exactly as you need it to be. We will be having a coworking session focused on working together to unit test our code. Beginners welcome!

If you test your code all the time, you can come by and be a helper for those who are just starting out!

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday, June 14, 6:10-7:30pm
**Instructor**: NA
**What to bring**: Laptop with your code on it!

**Comment by mi-lee** [comment]
What exactly are we unit testing? Pipelines, ETL jobs, or just basic intro to unit tests?

**Comment by linamnt** [comment]
Hi @mi-lee this is aimed to be more of a basic intro to unit tests.
