### ISSUE TITLE
 Git: Continuous Integration and Testing - June 21

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#104]
Continuous Integration (CI) is a development practice where you integrate code into a shared repository frequently e.g. via Git. Each integration can then be verified by automated tests/builds. We will briefly go over these concepts and how you can use CI in GitHub via [travis CI](https://travis-ci.org/) in your projects (such as for building websites, running unit tests, generating files, etc). 

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday, June 21, 6:10-7pm
**Instructor**: @lwjohnst86 
**What to bring**: Laptop with the following installed:
- Git (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- A GitHub account (https://github.com/)

**Comment by lwjohnst86** [comment]
Please also create an account on https://travis-ci.org/. It will link with your GitHub account.

**Comment by mbonsma** [comment]
Livestream is here: https://www.youtube.com/watch?v=9gvf_IMCuQ0

**Comment by lwjohnst86** [comment]
Travis works with R when there is a DESCRIPTION file. It can be empty. See the repo: https://github.com/lwjohnst86/testing_ci_r
