### ISSUE TITLE
R: dplyr and magrittr - July 19

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#108]
Using the R packages `dplyr` and pipes a la bash via `magrittr`, we get really powerful tools for data manipulation. 

`dplyr` is built around 5 verbs. These verbs make up the majority of the data manipulation you tend to do. You might need to:
- Select certain columns of data.
- Filter your data to select specific rows.
- Arrange the rows of your data into an order.
- Mutate your data frame to contain new columns.
- Summarise chunks of you data in some way.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday, July 19 6:10pm-7pm
**Instructor**: @aays
**What to bring**: Install [R](https://www.r-project.org/), [RStudio](https://www.rstudio.com/products/rstudio/download2/), and make sure you have the following packages:
```
install.packages("dplyr", dependencies = TRUE)  

install.packages("magrittr", dependencies = TRUE)
```

**Comment by mbonsma** [comment]
Live stream is [here](https://www.youtube.com/watch?v=qO4ZXzyiulM)!
