### ISSUE TITLE
Coworking session (for real this time)

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#11]
Past coworking sessions have turned into (very excellent) discussions instead of work time, as was recently pointed out. Let's try a real coworking session, where we get together with projects to work on and then sit in the same room and work on them, asking questions and showing off progress as we go. Check out the [handbook](http://mozillascience.github.io/studyGroupHandbook/event-types.html) to get the idea. 

**When:** September 10, 2015, 6:00 pm - 7:30 pm
**Where:** McLennan Physics building Rm. 408
**Preparation:** Bring a project to work on and a tweet-length description to share.

Directions to MP408:
Room 408 is in the Burton Tower, 4th floor.
From St. George Street: go in the main doors and turn left, then right (through three sets of doors) until you hit the elevators. 
From Huron Street: go in the doors and turn right, then right again (through three sets of doors) until you hit the elevators. 
From Russell Street: go in the doors and turn left (one set of doors), you'll be right at the elevators.

**Comment by JingjingHuang** [comment]
hi, so I just go to Room 408 on that day? Should I register something before?
