### ISSUE TITLE
Collaborating with others using GitHub - Aug 2

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#110]
Git and Github are tools not only for version control of your own code, but are widely used for collaborative team coding! Learn more about how you can use Git collaboratively on a project, the genereal workflow as well as details about the step-by-step process.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday August 2nd, 6:10-7pm
**Instructor**: @chungkky
**What to bring**:
Bring a laptop with Git installed (see instructions below) and make an account on [GitHub](https://github.com/join?source=header-home). It's free! 
### Git

Installation instructions for Git can be found on the [Git download site](https://git-scm.com/book/en/Getting-Started-Installing-Git)
- On Windows: Download the `.exe` file from this
  [Github link](https://msysgit.github.io) and run it.
- On Mac: To use the graphical Git installer, download from this
  [SourceForge link](https://sourceforge.net/projects/git-osx-installer/)
- On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by linamnt** [comment]
Note, if you are having any problems with installation or other issues, we will be at MP408 at starting from 5:30 today to help with set-up and to answer questions.

**Comment by chungkky** [comment]
Kathy's Etherpad [](https://etherpad.wikimedia.org/p/2017-08-02_UTCoders_GitCollab)
