### ISSUE TITLE
R: Resampling Techniques (Bootstrapping & Permutation Testing) - Aug 16th

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#112]
**Resampling techniqes**, or simulation methods, refers to the statistical methods that use the observed data to produce new hypothetical samples (resamples or shuffles of the data) that mimic the underlying population, which can inform the precision/accuracy or significance of other statistics performed on the data. We will go over **Bootstrapping** and **Permutation Testing**, two common forms of resampling techniques. The language we will be using is R. 

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday, August 16th, 6:10-7pm
**Instructor**:  @lwjohnst86
**What to bring**: 
Install [R](https://www.r-project.org/)  
Install [RStudio](https://www.rstudio.com/products/rstudio/download2/)  
More information to come.

**Comment by lwjohnst86** [comment]
Make sure to install the following packages:

```
install.packages(c("boot", "coin"))
```
