### ISSUE TITLE
Introduction to R - September 14

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#116]
A brief introduction to R programming. No experience is necessary to attend this lesson.

Where: MP408
When: Thursday, Sep 14, 6pm-7pm
Instructor: @aays
What to bring: A laptop with [R](https://www.r-project.org/) and [RStudio](https://www.rstudio.com/products/rstudio/download/) installed.

Please install the `dplyr` and `tidyr` packages by typing the following into RStudio console:

```install.packages(c('dplyr', 'tidyr')) ```

**Comment by linamnt** [comment]
Correction:
When: Thursday September 14th, 6-7pm.

**Comment by QuLogic** [comment]
Live stream is [here](https://youtu.be/b74V54VFL98).

**Comment by mbonsma** [comment]
The recording of the live stream is [here](https://www.youtube.com/watch?v=b74V54VFL98)!
