### ISSUE TITLE
Introduction to Python - Sept 28th

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#118]
Learn the basics of programming in Python. No prior experience in programming or Python is necessary.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Thursday, September 28th, 6pm
**Instructor**: @joelostblom 
**What to bring**: 
- A computer with Python installed:
   - We highly suggest using the Anaconda distribution of Python ([setup instructions here](https://uoftcoders.github.io/studyGroup/lessons/r-python-conda-setup/)) which will have many useful packages included and their dependancies

**Comment by joelostblom** [comment]
Can this be an intro to python and data analyses with pandas? Similar to how the R lecture is structured, still not require any previous knowledge, but the focus being on analyzing data, rather than general programming? I can do either version, just curious.

**Comment by linamnt** [comment]
I think that's fine as long as you bring people to the point where using packages like pandas and numpy and the functions in them make sense which I'm sure you will do very well :+1:

**Comment by msshane** [comment]
Can these trainings be open to non-UofT peeps as well?

**Comment by mbonsma** [comment]
@msshane yes for sure! Anyone is welcome to come.

**Comment by joelostblom** [comment]
Today's lesson will include an introduction to Python and how to use the Python packages `pandas` and `seaborn` to analyse and visualize spreadsheet-like data. To follow along, [view the lecture online here](https://nbviewer.jupyter.org/github/UofTCoders/studyGroup/blob/gh-pages/lessons/python/intro-data-analysis/from-spreadsheets-to-pandas-extended.ipynb).

**Comment by joelostblom** [comment]
Thanks everyone for coming out yesterday!
Here are a few resources to learn more about the topics we discussed (will soon be included in the notebook linked above):

- [Introduction to `pandas`](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [Lessons for new `pandas` users](http://pandas.pydata.org/pandas-docs/stable/tutorials.html#lessons-for-new-pandas-users)
- [The `seaborn` gallery](http://seaborn.pydata.org/examples/index.html)
- [The `seaborn` tutorials](http://seaborn.pydata.org/tutorial.html)
- [The `matplotlib` gallery](http://matplotlib.org/gallery.html) is another great resource. We did not practice using `matplotlib` explicitly in this notebook, but the plotting techniques from `pandas` and `seaborn` are layers on top of the `matplotlib` library, so we have been using it indirectly.
