### ISSUE TITLE
Introduction to Machine Learning - Oct 19th

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#121]
Machine learning crosses the boundaries of discipline and is found everywhere these days from our Netflix recommendations to how banks catch fraudulent transactions. This session will be an overview of important concepts behind machine learning and what it actually entails in more a lecture style session.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Thursday, October 19th, 6:10pm - 7pm
**Instructor**: @ralle123
**What to bring**: No need to bring a laptop to this session unless you'd like to take notes on it.

**Comment by linamnt** [comment]
@ralle123 Could you shoot me an email at uoftcoders@gmail.com when you get the chance, just to get a quick update regarding the lesson and to help to plan for the scikit learn lesson? Thanks!

**Comment by VinLau** [comment]
Hi, will this lecture (even though it is not a code-together) be televised remotely? I can't make it in-person this week.

**Comment by fvc23** [comment]
Will this lecture be streamed online? I won't be able to make it in person this week.

Thanks

**Comment by linamnt** [comment]
Yes, we will do our best to stream this lecture. Visit this issue to get
the link.

Thanks for your interest.

**Comment by fvc23** [comment]
visit which issue?

**Comment by joelostblom** [comment]
Once the lecture begins, we will post the live stream link in a comment here (and it will also be available via YouTube after the event).

**Comment by fvc23** [comment]
Hi Joe & Lina can you please post the link to the event.

Thanks

**Comment by linamnt** [comment]
Hi not sure how you're responding here, but it will be posted right here where we currently are discussing. Cheers. https://github.com/UofTCoders/Events/issues/121

**Comment by QuLogic** [comment]
Apologies for not posting this on the day itself, but here is the link to the stream: https://youtu.be/156rPHw9XxY
