### ISSUE TITLE
Intro to Git

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#13]
## Introduction to Git

Workflows, version control - what's the deal with [Git](https://git-scm.com/)? Come out to an Intro to Git session presented by @lwjohnst86. This is a repeat of a session held in the summer, and you can find the lesson plan [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/git/lesson.md). No prior Git experience is necessary, all are welcome.

**When:** Wednesday, September 23, 2015, 6 pm - 7 pm
**Where:** MP 408 ([Mclennan Physical Labs](https://www.google.ca/maps?q=mclennan+physical+labs&es_sm=122&um=1&ie=UTF-8&sa=X&ved=0CAcQ_AUoAWoVChMIoI3D7v-RxgIViEySCh34tAQ3), in the Burton tower)
**What to bring:** Computer, charged if possible, with Git installed (instructions below). If you don't have a Github account yet, now would be a good time to do that too.

### Git ###

Installation instructions for Git can be found on the
[Git download site](http://git-scm.com/book/en/Getting-Started-Installing-Git)

* On Windows: Download the `.exe` file from this
  [Github link](http://msysgit.github.io) and run it.

* On Mac: To use the graphical Git installer, download from this
  [SourceForge link](http://sourceforge.net/projects/git-osx-installer/)

* On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by sohnyrin** [comment]
HI ! In the agenda it says 7 to 8, does it start at 6 or 7? thanks :)

**Comment by mbonsma** [comment]
It starts at 6, the calendar was wrong (I fixed it now). Thanks for pointing that out!

**Comment by 1AVA** [comment]
Hi Madeleine, a couple of us are here but we don't see anyone else.
Sent wirelessly from my BB rouge.
Envoyé sans fil par mon terminal mobile BB rouge.

-----Original Message-----

**Comment by lwjohnst86** [comment]
Oh, sorry, the session was yesterday!! Sorry for the confusion, it must 
have been lost in the communications! :(
