### ISSUE TITLE
Introduction to R - January 11

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#131]
A brief introduction to R programming. No experience is necessary to attend this lesson.

Where: [MADLab at Gerstein ](https://goo.gl/maps/2916Y54jQkx)*
When: Thursday, January 11, 6:10pm-7pm
Instructor: @lwjohnst86 
What to bring: A laptop with [R](https://www.r-project.org/) and [RStudio](https://www.rstudio.com/products/rstudio/download/) installed.

- Please install the dplyr and tidyr packages by typing the following into RStudio console:
```install.packages(c('dplyr', 'tidyr'))```

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by lwjohnst86** [comment]
The code for the lesson is available [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r/intro/session-2018-01-11.Rmd)
