### ISSUE TITLE
Machine Learning for Computational Biology using R

### ISSUE THREAD

**Issue by SaraMahallati** [UofTCoders/Events#135]
If you already know the basics of machine learning and you want to gain more knowledge and practice, this session is for you. 

We will briefly go over some tips about how to avoid common mistakes and good practices in computational biology. We will then go over a supervised learning algorithm, k-nearest neighbours (k-NN) and practice on applying the algorithm to a cancer sample dataset, using R. 

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**:  Thursday, Feb 1st, 6:10pm
**Instructor**: @davidechicco
**What to bring**: A laptop with R and RStudio installed. 
- please install the "class" and "gmodels" libraries by typing the following into RStudio console:
```install.packages(c('class','gmodels'))```
- please download the two files from [this gist](https://gist.github.com/QuLogic/527fd30f250cf7f0207a84a6f261bfea)

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by davidechicco** [comment]
Please also download the following two files:

2 - Download the prostate cancer data file from the following link:
[http://www.bit.ly/prostate_cancer_DRE](http://www.bit.ly/prostate_cancer_DRE)

3 - Download the R script_knn.r file (in the same folder of your data
file) from the following link:
[https://drive.google.com/open?id=0B6J6MgNW0kFmWUFya1haLVczenc](https://drive.google.com/open?id=0B6J6MgNW0kFmWUFya1haLVczenc)

Thanks

**Comment by QuLogic** [comment]
Both files as a gist (for easier previewing): https://gist.github.com/QuLogic/527fd30f250cf7f0207a84a6f261bfea

**Comment by linamnt** [comment]
Solution file for the exercise yesterday: https://gist.github.com/linamnt/b7677e71415a3c0d30dd33b9ded4d200
