### ISSUE TITLE
ggplot2 in R - Feb 15

### ISSUE THREAD

**Issue by SaraMahallati** [UofTCoders/Events#136]
ggplot2 is a great and versatile package in R for plotting your data. We will do a code-a-long showing you different types of plots and how to customise them.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday Feb 15, 6:10 pm
**Instructor**: @aays 
**What to bring**: A laptop with R and RStudio installed. 
- please install the "ggplot2" and "plotly" libraries by typing the following into RStudio console:
```install.packages(c('ggplot2','plotly'))```

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by mbonsma** [comment]
The livestream is [here](https://www.youtube.com/watch?v=i_BgxbBjl5A)!
