### ISSUE TITLE
Image Processing in Python - Feb 8

### ISSUE THREAD

**Issue by SaraMahallati** [UofTCoders/Events#137]
This is an introductory tutorial on image processing using Python packages. We will do a code along to understand image data types, manipulate and prepare images for analysis such as image segmentation.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday Feb 8, 6:10 pm
**Instructor**: @nsahin 
**What to bring**: Bring a laptop computer, and download Python 3 using [Anaconda](https://continuum.io/downloads) which includes Python, IPython, NumPy, and many other useful packages. We highly recommend using Anaconda if you do not yet have Python. 

Here are [instructions for installing Anaconda](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md) 

We are going to use these two image processing libraries, Opencv-python, and PILLOW, please install them beforehand: 
pip install opencv-python
pip install PILLOW

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by SaraMahallati** [comment]
link to the image for the lesson:
https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/image-processing/yeast_colony_array.jpg

**Comment by mbonsma** [comment]
Link to video recording of session: https://www.youtube.com/watch?v=e2v2O2H52Hc
