### ISSUE TITLE
Open Source Tools for Graphic Design: Inkscape  - Feb 22

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#138]
We will learn to use Inkscape, a cross-platform open source graphic design software. 
We will cover:
 - why use vector graphics instead of rasterized,
 - basic interface features of Inkscape
 - paths/shapes
 - strokes/fills
 - groups/layers/alignment
 - resizing drawing region and exporting
 - importing from other sources (e.g. plots generated in R or Python)

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday Feb 22, 6:00 pm 
**Instructor**: @jladan
**What to bring**: Your laptop with Inkscape installed: https://inkscape.org/en/release/0.92.2/

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by SaraMahallati** [comment]
Here are the sample figures that may be used during the lesson: 

![download](https://user-images.githubusercontent.com/12663563/36463181-2ef19252-1696-11e8-91c1-a8b9d16dd5b3.jpg)
![dvelj2hx0aadkcd](https://user-images.githubusercontent.com/12663563/36463182-2efe6248-1696-11e8-8484-fca55604f59d.jpg)
[grad-perturbations.pdf](https://github.com/UofTCoders/Events/files/1742870/grad-perturbations.pdf)
[model-cartoon.pdf](https://github.com/UofTCoders/Events/files/1742871/model-cartoon.pdf)

**Comment by mbonsma** [comment]
Livestream is [here](https://www.youtube.com/watch?v=aidR9tSY11s)!

**Comment by QuLogic** [comment]
Image for current demo:
https://github.com/jladan/studyGroup/blob/gh-pages/lessons/misc/inkscape-intro/phage_flow_demo.svg
