### ISSUE TITLE
What is Blockchain? - March 8

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#139]
If you have heard about blockchain and cryptocurrencies, but are still puzzled, this workshop is for you. 
In just 1 hour you will learn about:
- Decentralization
- Nodes
- Crypto currencies
- Mining
- Cryptography
- Accounts
- Wallets
- Private keys
- Blocks
- Hash
- GAS
- Smart Contracts

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**:  March 8, 6:00pm
**Instructor**: Elena from *CryptoChicks* 

*About CrytoChicks*
[CryptoChicks ](https://cryptochicks.ca) is a non for profit organization that makes learning blockchain easy and fun. We focus on educating and supporting women in blockchain. We believe addressing  the gender gap problem will make blockchain technology more sustainable.

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by andreimouraviev** [comment]
Is this talk open to everyone?

**Comment by SaraMati** [comment]
Hi Andrei
yes, all the sessions are open to everyone. We also try to livestream our sessions. The link will be posted here when the session starts

**Comment by andreimouraviev** [comment]
Thanks!

**Comment by andreimouraviev** [comment]
Hope to join via livestream :)

**Comment by QuLogic** [comment]
Live stream will be here: https://youtu.be/Q6k_-g0QREU

**Comment by linamnt** [comment]
Don't forget to also check out the blockchain hackathon for women in April 6-8 at MaRS. Cryptochicks will provide a free online education for all female participants through their sponsor BlockGeeks. Plus provide a mentorship before and during the hackathon. 

 Please take a look at event website https://Cryptochickshackathon.com 

Thanks again to Cryptochicks for the lesson and all who attended and watched!
