### ISSUE TITLE
Neural Networks in Python - March 22nd

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#142]
If you're interested in implementing your own neural networks architectures for machine learning problems, come learn about very well-used Tensorflow, and Keras (which uses Tensorflow backend) in Python to do just that. 

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, March 22nd, 6-7pm
**Instructor**: @SaraMati & @nsahin  
**What to bring**: 
- have an installation of Python 3 on your laptop, we recommend [Anaconda](https://www.anaconda.com/download/)
- install [Tensorflow](https://www.tensorflow.org/install/)
- install [Keras](https://keras.io/#installation) If you've successfully installed Tensorflow, you should be able to do the following:
`pip install keras`

If you have trouble installing any of these, you can drop by earlier (starting 5:50pm) and one of our team will help you install. 

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by sdlm** [comment]
Hi all!
Are you will write some video ?

**Comment by gabenespoli** [comment]
Will this session be available online afterwards? I'm not able to be at a computer to watch the live stream at 6.

**Comment by lwjohnst86** [comment]
We try to get each session recorded, so this one should be as well. I would also like to watch it :)

**Comment by gabenespoli** [comment]
Great thank you! Where will the link to the video be posted?

**Comment by lwjohnst86** [comment]
Usually on this page.

**Comment by mbonsma** [comment]
Shortly before the event starts tonight we'll post the link here to the livestream which will be saved as a recording.

**Comment by mbonsma** [comment]
The livestream is here: https://www.youtube.com/watch?v=K3mdzB_yj5E

**Comment by QuLogic** [comment]
It might be a little faster to install from conda-forge, if you haven't already, and are not on one of the supported systems in the instructions: `conda install -c conda-forge keras tensorflow`. The default backend for keras is Theano, so you may have to set the `KERAS_BACKEND=tensorflow` environment variable before starting Python to ensure tensorflow is used.
