### ISSUE TITLE
Intermediate Topics in R - March 1

### ISSUE THREAD

**Issue by lcoome** [UofTCoders/Events#143]
More intermediate level topics in R.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: **March 1st**
**Instructor**: @lcoome
**What to bring**: A laptop with R and RStudio installed.
Instructions:
[https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md)
Have the packages forcats and stringr installed

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by QuLogic** [comment]
Live stream is here: https://youtu.be/qaDIAJRoGGQ

**Comment by QuLogic** [comment]
Lesson content: https://uoftcoders.github.io/studyGroup/lessons/r/intermediate/lesson/
