### ISSUE TITLE
Academic Workflows - March 29

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#145]
We will learn some handy tips and discuss some tools John has developed for [reproducible research with Jupyter notebooks](https://github.com/JohnGriffiths/ipynb-workdocs)  and maintaining a [digital lab notebook/technical blog ](https://johngriffiths.github.io/LabNotebook/about-the-notebook.html). 
 
**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**:  Thursday, March 29, 6-7pm
**Instructor**: @JohnGriffiths, (PhD, Cognitive Neuroscience, University of Cambridge), Post-doctoral Fellow in the McIntosh Lab at the Rotman Research Institute and in the Lefebvre Lab at the Krembil Research Institute
**What to bring**: have an installation of Python 3 on your laptop (we recommend Anaconda) with Jupyter notebook. 

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by QuLogic** [comment]
The first link: https://github.com/JohnGriffiths/UofT_Coders_Talk_March2018
Other links are given above.

**Comment by SaraMati** [comment]
the link to the live stream
https://hangouts.google.com/hangouts/_/bedvj45idbfkpjbjlobpqoafhme

**Comment by mbonsma** [comment]
Here's the recording of the session: https://www.youtube.com/watch?v=dVGVBMb6kzo
