### ISSUE TITLE
Intro to Statistics in R - May 24th

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#156]
R is a powerful tool for doing simple to complex statistics, after all, that's what it was originally designed for. Our introduction to doing statistics in R lesson will go over basic descriptive and inferential statistics (e.g. regression, ANOVA). Please come with RStudio installed along with the following packages:

`install.packages("car")`
`install.packages("psych")`
`install.packages("multcomp")`

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, May 24th, 6:10-7:30pm
**Instructor**: @lcoome 
**What to bring**: TBD

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by HeidyMM** [comment]
Sorry I have to miss this R session... will you be offering it again in the future? TY

**Comment by linamnt** [comment]
HI Heidy, We do rerun our lessons once a year or so depending on their popularity. Also, we record all our sessions for you to watch on youtube afterwards, the livestream link is posted here before each session, so that's one way to follow along even if you aren't able to attend.

**Comment by mbonsma** [comment]
Here's the link the the recording of the live stream! https://www.youtube.com/watch?v=A7AD40fpLK8
