### ISSUE TITLE
Intermediate Statistics in R - May 31st

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#157]
Building from our previous lesson, we will go over more advanced statistical analyses using the R programming language, and especially cases where your data may be a little bit messy or you might be working with repeated-measures data (also known as hierarchical data or within-subject data). We'll assume that you are familiar with basic linear regression (e.g. testing if x predicts y) and statistics basics (e.g. how to interpret a p-value), but we will do a brief review and explain everything else as we go! 

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, May 31st, 6:10-7:30pm
**Instructor**: Zoe Francis, graduate student at Department of Psychology
**What to bring**: your laptop, with R studio and the following packages installed:
psych
lme4
lmerTest

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by mbonsma** [comment]
The live stream is [here](https://www.youtube.com/watch?v=gqqbZq55n4w)!

**Comment by SaraMati** [comment]
unfortunately, we couldn't live stream this session due to technical difficulties
