### ISSUE TITLE
Intro LaTeX - June 21

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#158]
LaTeX is the standard typesetting package for mathematical and scientific research. It is a powerful tool for making high quality, well-formatted documents. It separates content from formatting, allowing you to focus on the content more easily without being bogged down by constantly making adjustments to formatting as you make changes to content.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, June 21, 6:10pm-7:00pm
**Instructor**: @SaraMati 
**What to bring**:    You have two options: 
1) Install latex on your computer: 
- [MacTex](https://tug.org/mactex/mactex-download.html) for Mac
- [MiKTeX](https://miktex.org/howto/install-miktex) for windows 
- Install latex : sudo apt-get install texlive-full and Install the editor sudo apt-get install texmaker

2) If you like to work online:
Make an account on [ShareLaTeX](https://www.sharelatex.com/) or [Overleaf](https://www.overleaf.com/) so you can work along through the presentation.

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by mbonsma** [comment]
The live stream is here: https://www.youtube.com/watch?v=l4Nd9S9IKgo

**Comment by migotist** [comment]
@SaraMati .. Hi .. Thanks again for the session. Can we have the link to the final document that you said you will post ?

**Comment by SaraMati** [comment]
Here is the link to lesson material: the source file and the accompanying files (a few figures and a .bib file for references) to compile the full document : 
https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/misc/latex-intro/Intro-to-Latex-Sara

**Comment by migotist** [comment]
@SaraMati...Thank you. It sure is useful
