### ISSUE TITLE
Intro to Bash - June 14

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#159]
This introduction to BASH aims to make participants capable of working from the command line in Unix environments. The focus of this lesson will be to learn common file system tasks and to use built-in tools to make your work more efficient (and fun!). This is a beginner level workshop, so no previous knowledge is required. A few intermediate level concept will be introduced, but we will not go into scripting in BASH.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, June 14, 6:10pm-7pm
**Instructor**: @joelostblom 
**What to bring**: 

Your laptop. 

Windows: Make sure to have [Git Bash](https://git-scm.com/download/win) if you use Windows, or [enable Bash shell](http://www.laptopmag.com/articles/use-bash-shell-windows-10) if you have a newer update of Windows 10. 

Linux and Mac: These will already have Bash installed by default.

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by WKMTO** [comment]
I'd like to join, but is this only open for UofT staff/students?

**Comment by linamnt** [comment]
This is open to all @WKMTO Thanks for your interest and see you there!

**Comment by SimbaDarko** [comment]
This sounds amazing. I'd be interested in dropping by as well.

**Comment by mbonsma** [comment]
[Here's the link](https://www.youtube.com/watch?v=KbIpcy6G_bE) to the live stream.

**Comment by joelostblom** [comment]
If we have time at the end, we will work some with text files, so I am posting the link to [download them here](https://www.dropbox.com/s/xgbbtbgjpck6wu7/news.zip?dl=0)

**Comment by paraish** [comment]
Hi guys, is the live stream down?

**Comment by joelostblom** [comment]
Sorry about that @paraish, the live stream and recording got cut off due a technical issue. The video from the last bash lecture is [available here](https://www.youtube.com/watch?v=-1E61HswswU), the content is largely the same as what was taught this time.

**Comment by joelostblom** [comment]
Thanks for coming out today everyone! As promised, here are links to some of the things I mentioned that we didn't discuss in depth during the lecture. Let me know if I forgot something!

- [Permanently create an alias](https://askubuntu.com/questions/17536/how-do-i-create-a-permanent-bash-alias), e.g. make `rm` always execute `rm -i`
- `autojump` is used to jump between directories faster and can be installed on [multiple operating systems](https://github.com/wting/autojump).
- How to install the `tree` command on [MacOS](https://superuser.com/questions/359723/mac-os-x-equivalent-of-the-ubuntu-tree-command) and [Windows](https://superuser.com/questions/531592/how-do-i-add-the-tree-command-to-git-bash-on-windows)
- The file manager [`ranger`](https://www.youtube.com/watch?v=qooLR8NmYKs)
- [`dos2unix`](https://stackoverflow.com/questions/20368781/anything-like-dos2unix-for-windows/31999399#31999399), only if you have created a BASH script on Windows that complains about incorrect line endings.

**Comment by joelostblom** [comment]
You can also try something fun like this to see your most used command =)

```bash
history | tr -s ' ' | cut -d ' ' -f3 | sort | uniq -c | sort -n | tail
```

**Comment by migotist** [comment]
.. It was quite informative and triggered my curiosity . I found a bash profile that did almost all that joel mentioned in the TUT and I am using that at the moment. Also added Tree to bash !! Thanks very Big @joelostblom
