### ISSUE TITLE
Markdown and Pandoc - June 28

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#161]
Learn how to use Markdown, Pandoc to convert between file formats (PDF, html, Word, etc.)

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, June 28th, 6:10-7:00pm
**Instructor**: @linamnt 
**What to bring**: 

### Getting Started (what to install before class)

- Install [Pandoc](http://pandoc.org/installing.html)
- Install LaTeX: [TeXLive (Linux)](http://www.tug.org/texlive/), [MacTeX (Mac)](http://www.tug.org/mactex/), [MikTeX (Windows)](https://miktex.org/)

Whether you're doing something like `sudo apt-get pandoc && apt-get texlive` or `brew install pandoc && brew cask install mactex`, if you can run `pandoc -v` and `pdflatex -v` in a terminal, you're good to go.

***NOTE: NEW LOCATION**
We will be holding this session at MADLab in Gerstein. MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. 

**Directions:** Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by mbonsma** [comment]
The live stream is [here](https://www.youtube.com/watch?v=9YCIRHLpO24).

**Comment by linamnt** [comment]
https://github.com/citation-style-language/styles <- This github repo has all the citation style languages for pretty much every journal style out there. Use the "Find File" function to search through, and copy the raw and save in your document folder.
