### ISSUE TITLE
Intro to Python - July 19

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#165]
The basics of the programming language Python with a beginner-friendly code-along.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, July 19th, 6:10-7 pm
**Instructor**: @joelostblom 
**What to bring**: Bring a laptop computer, and download Python (preferably 3, but 2 is also fine) using [Anaconda](https://continuum.io/downloads) which includes Python, IPython, NumPy, and many other useful packages. We highly recommend using Anaconda if you do not yet have Python. 

If you're on Mac or Linux, you probably already have Python installed. 

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by joelostblom** [comment]
This lesson will introduce participants to how to program in Python and is specifically focused on how to use Python for data analysis. The lesson will be based on [this content](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/intro-data-analysis/from-spreadsheets-to-pandas-extended.ipynb).

**Comment by joelostblom** [comment]
Data set url https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv

**Comment by joelostblom** [comment]
As mentioned during the lecture, here are the links to the material of our workshop in how to use Python for data analysis:

- Day 1 morning: https://nbviewer.jupyter.org/github/UofTCoders/2018-07-12-utoronto/blob/gh-pages/code/1-programmatic-data-analyses.ipynb
- Day 1 morning part 2: http://www.datacarpentry.org/spreadsheet-ecology-lesson/
- Day 1 afternoon: https://nbviewer.jupyter.org/github/UofTCoders/2018-07-12-utoronto/blob/gh-pages/code/2-data-analysis-in-python.ipynb
- Day 2 morning: https://nbviewer.jupyter.org/github/UofTCoders/2018-07-12-utoronto/blob/gh-pages/code/3-data-wrangling-and-viz.ipynb
- Day 2 afternoon: https://nbviewer.jupyter.org/github/UofTCoders/2018-07-12-utoronto/blob/gh-pages/code/4-advanced-viz.ipynb

We will likely teach another iteration of this workshop in September. Subscribe to notifications of new events in this repository or keep an eye out on [our homepage](https://uoftcoders.github.io/studyGroup/) to find out more details!
