### ISSUE TITLE
 Measures of association and statistical testing of hypotheses in Python - July 26

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#166]
Coverage:
- Introduction/Motivation
- Effect size and its statistical significance
- Association between two continuous, ordinal and categorical variables
- Implications to data science and machine learning

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, July 26, 6:10-7:30 pm
**Instructor**: Tomas Tokar, Research associate at Jurisica Lab at Krembil Research Institute
**What to bring**:  Please have installed: Python >= 3.4, NumPy, SciPy, Pandas >= 0.21, Scikit Learn >= 0.19, and Jupyter Notebok, or Jupyter Lab

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by mbonsma** [comment]
Here's the [live stream recording](https://www.youtube.com/watch?v=e3V57aN23TY).
