### ISSUE TITLE
Web scraping - August 2

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#167]
Introduction to Web Scraping in Python: Web scraping is about downloading structured data from the web, selecting some of that data, and passing along what you selected to another process. 

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, August 2, 6:10-7:00 pm 
**Instructor**: Riyad Parvez
**What to bring**: Your laptop with Python and preferably Jupyter lab/notebook installed
Please install Google Chrome, and the following Python packages:
- httpie (neat command line utlity)
- requests (to retrieve content)
- beautifulsoup4 (to scrape HTML web page)

`pip3 install -U httpie requests beautifulsoup4`

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by QuLogic** [comment]
The example files are here: https://gist.github.com/riyadparvez/43877eddc8de68329c84f984b0edaa45
