### ISSUE TITLE
Intro to Git - August 16

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#169]
Learn how to take advantage of version control for your projects and why it can be useful. We will be focusing on Git, a popular piece of software that does version control. This session is geared towards complete beginners - if you've never touched Git before, this is for you!

**Where**: MADLab* at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**:  Thursday, August 16 , 6:10pm-7pm
**Instructor**: @QuLogic
**What to bring**:  a laptop with Git installed (see instructions below). Optional: make an account on [GitHub](https://github.com/join?source=header-home).

### Installing Git
Installation instructions for Git can be found on the [Git download site](https://git-scm.com/book/en/Getting-Started-Installing-Git)
- On Windows: Download the `.exe` file from this
  [link](https://git-scm.com/download/win) and run it.
- On Mac: To use the graphical Git installer, download from this
  [SourceForge link](https://sourceforge.net/projects/git-osx-installer/)
- On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

 **Watch:** This event will be [streamed live](https://www.youtube.com/watch?v=WYc0DI6Ywpc). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by QuLogic** [comment]
Editor config: http://swcarpentry.github.io/git-novice/02-setup/

**Comment by QuLogic** [comment]
Sandbox: https://github.com/UofTCoders/sandbox-2017
