### ISSUE TITLE
Virtualization vs. Docker Images -- August 30

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#171]
Continuing the contributing to open source projects theme, we will be looking at alternatives on setting up your working environment. We will be looking at the python ecosystem and looking at differences of working with python virtual environments and docker.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, August 30, 6:10-7:00 pm 
**Instructor**: @ralle123
**What to bring**: Please bring a machine with docker installed.

For virtual environments we will use the following:
conda-  https://www.anaconda.com/download/
pip install virtualenv

To install docker-
https://docs.docker.com/install/

 **Watch:** This event will be [streamed live](https://www.youtube.com/watch?v=3cTnjHTq0Ik). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by ralle123** [comment]
Continuing the contributing to open source projects theme, we will be looking at alternatives on setting up your working environment. We will be looking at the python ecosystem and building a docker image, python virtual environment and how to document using sphinx. Please bring a machine with docker and sphinx installed.

To install docker-
https://docs.docker.com/docker-for-mac/install/

To install sphinx-
http://www.sphinx-doc.org/en/master/usage/installation.html
