### ISSUE TITLE
Coworking, theme: bugs and pull reqs - September 6	

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#172]
A coworking session for working together on bugs and pull requests, but everyone is welcome even if you'll be working on something different. Check out the [handbook ](http://mozillascience.github.io/studyGroupHandbook/event-types.html)for more information about coworking sessions.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: Thursday, September 6, 6:10-7 pm 
**What to bring**: your laptop and a problem to work on

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by mbonsma** [comment]
This talk about open source etiquette might be good to discuss: https://www.youtube.com/watch?v=tzFWz5fiVKU&t=2970s
