### ISSUE TITLE
Lightning Demos: reproducible documents (reports, papers and thesis) - September 27

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#187]
What is your approach to creating reproducible documents? how do you use the capabilities in R, Python, Latex, pandoc, etc. to integrate your data analysis with writing your reports and other manuscripts? Come to this session and show your peers what is your workflow for creating reproducible documents or hear from others how they do it.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, September 27, from 18:10-19:00 pm
- **Skill level**: Beginner

*Watch*: This event will be [streamed live](). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)
         **Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by linamnt** [comment]
This is the lesson material I referenced in my demo: https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/misc/pandoc-intro
