### ISSUE TITLE
Intro to Python

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#19]
The very basics of the programming language Python. I will lead a beginner-friendly code-along based on a [previous lesson](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/python_basics) taught by @cczhu.

**When:** Thursday, October 22, 2015, 6pm - 7pm
**Where:** MP 408 (Mclennan Physical Labs in the Burton Tower)
**Preparation:** 
- Download Python (either [2](https://www.python.org/downloads/release/python-2710/) or [3](https://www.python.org/downloads/release/python-343/)). If you're on Mac or Linux, you probably already have Python installed. If this is the first time you're installing Python, I strongly recommend downloading and installing [Anaconda](http://continuum.io/downloads) which includes Python, IPython, sympy, numpy, and many other useful packages. It'll save you installing a bunch of common packages right away. 
- Recommended: install [IPython](http://ipython.org/install.html) (if you're not going the Anaconda route)
- Optional: Download and install a development environment (I use [WingIDE101](http://www.wingware.com/downloads/wingide-101/5.1.5-1))

**Comment by QuLogic** [comment]
BTW, is there no matplotlib this term?

**Comment by mbonsma** [comment]
@QuLogic None scheduled for this term. I'll put it on the list of potential topics for next term.
