### ISSUE TITLE
Intro Python with Numpy and Pandas - October 25

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#198]
This week, we will be learning how to perform data analysis in Python using numpy and pandas. The focus will be on analyzing data that is stored in a spreadsheet format. We will learn how to:
- import data from spreadsheets
- manipulate data 
- perform mathematical operations on data
- visualize data

 **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
 **When**: Thursday, October 25, from 18:10-19:00 pm
 **Instructor**: Amanda
 **Skill level**: intro

*Installation instructions*: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-python-r.md). Please ensure that you have Jupyter notebooks installed, as well as the following Python packages: numpy, pandas, seaborn, matplotlib. We recommend using Anaconda for the installations.

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=amo9hf66hhY). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by QuLogic** [comment]
Live stream is here: https://www.youtube.com/watch?v=amo9hf66hhY

**Comment by linamnt** [comment]
The Jupyter Notebook is here: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/intro/intro_data_analysis_AE.ipynb
