### ISSUE TITLE
R: Plotting with theme of Heatmaps - November  1

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#199]
Heatmaps are a useful tool for visualizing high-dimensional data. By using colour to represent values and cell ordering based on a clustered distance metric, patterns can be picked out of data for further analysis of sub-groups. This lesson will cover topic related to plotting heatmaps such as:

- input data format
- common distance measures
- common clustering methods
- generating static heatmaps
- adding metadata to your plot
- generating interactive heatmaps

**Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
**When**: Thursday, November  1, from 18:10-19:00 pm
**Instructor**: @eacton
**Skill level**: intermediate

*Installation instructions*: You will need to install the appropriate programs. See the R section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-python-r.md).

In addition to R and RStudio, please install the following packages:
pheatmap and heatmaply

install.packages('pheatmap')
install.packages('heatmaply')

*Watch*: This event will be [streamed live](http://youtu.be/bHdeK1ADGNI). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by nadiamuhe** [comment]
Hi! Where is the live stream for this session?

**Comment by SaraMati** [comment]
livestream is here:
http://youtu.be/bHdeK1ADGNI

**Comment by eacton** [comment]
The code from the plotting with heatmaps live session can be found here:     
https://github.com/eacton/Heatmaps/blob/master/heatmap_uoftcoders.R

Or with the data files and addition resource links at https://github.com/eacton/Heatmaps
