### ISSUE TITLE
Life's great programming challenges: brainstorming co-working session

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#2]
Let's get together and discuss some of the programming tasks that are common in our research. The goal of this session is to identify areas of programming focus that potentially span disciplines. That way, we can benefit from learning about what people in other fields are doing and possibly find new ways to approach 'classic' problems. For example: reading in large amounts of data efficiently, visualizing networks, matrix operations on large matrices, etc.  

**When:** July 16, 2015, 6pm onwards
**Where:** MP 408 (Mclennan Physical Labs, Burton Tower)
**Preparation:** Make a short list of what you see as the important programming challenges in your research or field to share with the group.

**Comment by mbonsma** [comment]
See you all at 6 for some idea-sharing! There will be snacks!

**Comment by lannajin** [comment]
Thanks for organizing the session today! Can I also recommend we create a calendar that can be imported into Google calendar or whatever people use (iCal?) to keep track of events?

**Comment by mbonsma** [comment]
We had a great discussion about things we'd like to see in future sessions. Some of the ideas have made it onto the [wiki](https://github.com/UofTCoders/studyGroup/wiki/Session-Proposals) - which anyone can edit and update - and some are listed under the [general programming session ideas](https://github.com/UofTCoders/studyGroup/issues/18) issue. Feel free to add to anything!
