### ISSUE TITLE
Python coding lightning demos

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#20]
Short 5-10 minute demonstrations of cool things you can do with Python, from a variety of presenters on a variety of topics.

Presenters:
* Asher Pasha - getting data from RESTful web servers
* Dano Morrison (@jdpigeon) - Python Pandas DataFrames
* Elliott Sales de Andrade (@QuLogic) - 101 Reasons to use IPython; 25 Ways to Make Your Python Scripts a Million Times Faster
* Madeleine Bonsma (@mbonsma) - regular expressions in Python

(If you are a presenter, please feel free to add more detail about your proposed demo in the comments.)

**When:** Thursday, November 5, 2015, 6pm - 7:30pm
**Where:** MP 408 (Mclennan Physical Labs in the Burton Tower)
**Preparation:** 
Anyone is welcome to come regardless of Python experience level, but if you want to work through examples in Python, it's recommended that you come with Python installed and with some basic knowledge of Python.

- Download Python (either [2](https://www.python.org/downloads/release/python-2710/) or [3](https://www.python.org/downloads/release/python-343/)). If you're on Mac or Linux, you probably already have Python installed. If this is the first time you're installing Python, I strongly recommend downloading and installing [Anaconda](http://continuum.io/downloads) which includes Python, IPython, sympy, numpy, and many other useful packages. It'll save you installing a bunch of common packages right away. 
- Recommended: install [IPython](http://ipython.org/install.html) (if you're not going the Anaconda route)
- Optional: Download and install a development environment (I use [WingIDE101](http://www.wingware.com/downloads/wingide-101/5.1.5-1))

**Comment by jdpigeon** [comment]
In with a modest Pandas Dataframe introduction

**Comment by QuLogic** [comment]
Any numbers in the titles of my talks may be entirely fictitious.

**Comment by mbonsma** [comment]
@jdpigeon and @QuLogic, can you [add your lesson files](https://github.com/UofTCoders/studyGroup/wiki/Contributing-a-lesson) to the repo when you get a chance? (@QuLogic, if yours are the same as before, don't worry about it.)

**Comment by QuLogic** [comment]
Well, I mean, the IPython talk is round about the same, but I never wrote anything down except the title...
