### ISSUE TITLE
Python: Machine Learning with scikit-learn - November 22

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#202]
### Topics Covered
- Data Exploration & Validation
- Feature Engineering
- Algorithms
    - Linear Classification
    - Linear Regression
- Validation
     - k-fold cross validation
### Dataset  
Please download the following datasets:
* [Titanic Dataset](https://www.kaggle.com/c/titanic) for classification
  - [Train](https://gist.github.com/riyadparvez/4e4e1cefcf6d4ed7decded7f3f8646af)
  - [Test](https://gist.github.com/riyadparvez/569809de1b13f92205c0ce1a6410f8fc)
* [Housing Price Dataset](https://www.kaggle.com/c/house-prices-advanced-regression-techniques) for regression
  - [Train](https://gist.github.com/riyadparvez/bf71f0945bfe76b19746689895b4a1fd)  
  - [Test](https://gist.github.com/riyadparvez/7ff0cd1583fb4bcb606fb7facfc9c6c9)

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, November 22, from 18:10-19:00 pm
- **Instructor**: Riyad Parvez
- **Skill level**: Intermediate

*Installation instructions*: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-python-r.md). Please also install these packages: 

* [pandas](https://pandas.pydata.org/)  
* [scikit-learn](http://scikit-learn.org/stable/)   
* [sklearn-pandas](https://github.com/scikit-learn-contrib/sklearn-pandas)  
* [Dive](https://www.usedive.com/)
* Google hosted jupyter notebook: [Colab](https://colab.research.google.com/).  [Introductory tutorial on how to use colab](https://colab.research.google.com/notebooks/welcome.ipynb#forceEdit=true&sandboxMode=true&scrollTo=FlQq0SUepQbd)

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=HIGzQbHetCc). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by linamnt** [comment]
Stream Link: https://www.youtube.com/watch?v=HIGzQbHetCc
