### ISSUE TITLE
End of Term Holiday Social - December 13

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#210]
Join us to celebrate another semester with UofT Coders. Enjoy some refreshments on us while getting to know the exec, instructors and other community members! 
All welcome and bring your friends.

**Where**: [Fran's Upper Deck](https://goo.gl/maps/6DAtHaoZU6z)
**When**: December 13th, 6pm - 9pm

**Comment by QuLogic** [comment]
The reservation will be under Lina if you get there early.

**Comment by linamnt** [comment]
We're on the third floor!
