### ISSUE TITLE
Introduction to plotting with ggplot2

### ISSUE THREAD

**Issue by thesarahmeister** [UofTCoders/Events#22]
A brief introduction to the ggplot2 package and making simple graphs 

    When: Thursday, Nov. 26th, 2015, 6:00-7:00pm
    Where: MP 408 (Mclennan Physical Labs in the Burton Tower)

Preparation:

Install:

    R
    RStudio

Because internet is sporatic in MP408, please come to the session with dplyr, tidyr, and ggplot2 packages installed either by using the RStudio "Tools->Install packages" option or by typing these commands into the R console:

    install.packages('dplyr')
    install.packages('tidyr')
    install.packages('ggplot2')

**Comment by QuLogic** [comment]
Are you sure this isn't November 26th?

**Comment by thesarahmeister** [comment]
Yep! It is lol. My bad. I'll change it
