### ISSUE TITLE
R: Interactive Plotting with Shiny Apps - February 21

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#224]
Shiny allows us to make interactive web applications with R, without us having to get too entangled in Javascript, CSS or html (though knowledge of these languages allows for further customization). These apps are not too much work to create and make data more fun to explore and share. In this lesson we will explore:
- Shiny syntax for building our user interface and our server code.
- Incorporate html widgets, such as drop down menus and check boxes.
- Explore reactive programming, allowing for real time modification of plots and data tables.
- How to customise the look of our Shiny app using Shiny dashboards.

 **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
 **When**: Thursday, February 21, from 18:10-19:00 pm
 **Instructor**: Erica Acton
 **Skill level**: Intermediate

*Installation instructions*: You will need to install the appropriate programs. See the R section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md). Please also install these packages: **Shiny, shinydashboard, DT, tidyverse**

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=Pp3zMKq_G-0). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by eacton** [comment]
*Session Info:*

Shiny allows us to make interactive web applications with R, without us having to get too entangled in Javascript, CSS or html (though knowledge of these languages allows for further customization). These apps are not too much work to create and make data more fun to explore and share. In this lesson we will explore:

* Shiny syntax for building our user interface and our server code.

* Incorporate htmlwidgets, such as drop down menus and check boxes.

* Explore reactive programming, allowing for real time modification of plots and data tables.

* How to customize the look of our Shiny app using Shiny dashboards.

*In addition to R and RStudio, please install the following packages:*
shiny, shinydashboard, DT, tidyverse

**Comment by k-brego** [comment]
is todays lesson going to be streamed?

**Comment by SaraMati** [comment]
> is todays lesson going to be streamed?

yes, the link above is now pointing to the YouTube video

**Comment by eacton** [comment]
Here is the link to the lesson materials:

https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/r/shiny_2019
