### ISSUE TITLE
Co-working Session - February 28

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#225]
Bring something to work on whether it be data analysis, a Kaggle competition, making figures, setting up software or anything else you'd like to work on.

Ask for help and discuss. This is friendly, welcoming environment for coders of all levels from absolute beginner to advanced, and of course we know coding is great, but it can be a lot more fun when you're not alone.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, February 28, from 18:10-19:00 pm
- **Instructor**: NA
- **Skill level**: All Levels

**Note**: This event will be NOT be streamed live.

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by davidechicco** [comment]
Hi @SaraMati and UofT Coders all.

Thanks for organizing this session. The link to the installation instructions does not seem to work. Can you please fix it?

Thanks

-- Davide

**Comment by QuLogic** [comment]
I've fixed the link, though I think the specific packages needed for this lesson are not yet available.

**Comment by linamnt** [comment]
Hi Everyone, unfortunately, due to unforeseen circumstances, we will be rescheduling this to a later date. We will have a co-working session this week instead. Keep an eye out for the new date for this lesson. Thanks for understanding.

**Comment by davidechicco** [comment]
@QuLogic Thanks for the correction.

@linamnt Thanks for the update. Please edit the event details on the homepage [https://uoftcoders.github.io/studyGroup/#events](https://uoftcoders.github.io/studyGroup/#events) as well.
