### ISSUE TITLE
Full Text Search with SQLite and Python -  March  7

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#226]
SQLite is a software library that provides access to a lightweight, local, disk-based database.  It has a C-based API as well as interfaces for many other popular languages such as Python, and allows database access using a variant of the SQL language. “SQLite is built into all mobile phones and most computers and comes bundled inside countless other applications that people use every day.”

In this session we will start with a quick review of the basics of SQL and SQLite, then look at using SQLite’s FTS (Full Text Search) module, which lets you find stored documents using full-text-search. We will cover the basics of setting up a text index, constructing search queries, and then related concepts such as result snippets, matchinfo and tokenizers.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, March  7, from 18:10-19:00 pm
- **Instructor**: Mike
- **Skill level**: Advanced

*Installation instructions*: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md). 
We will use Python’s built-in SQLite module for the practice examples in this session. If you would like to follow along, please bring a laptop with a copy of Python 3 installed.

*Watch*: This event will be [streamed live](https://youtu.be/vaLIzN4t_44). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by linamnt** [comment]
The stream is here: https://youtu.be/vaLIzN4t_44

**Comment by QuLogic** [comment]
Sorry, meant to post this earlier, but the lesson content and example database are available here: https://uoftcoders.github.io/studyGroup/lessons/misc/sqlite-fts/lesson/
