### ISSUE TITLE
Information on the Air - Software Defined Radio - March 14

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#227]
Thanks to the mass manufacturing of digital video broadcast decoders, it's possible to obtain a RealTek chipset USB dongle with an antenna (somewhat like a sound card) for $20-$50 that allows your computer to receive, record, and examine significant portions of the radio frequency spectrum, e.g. 25MHz - 1.7GHz.  More expensive transceiver devices have a wider range (1MHz - 6GHz), and they allow you to transmit as well.  

Examples - 
https://www.nooelec.com/store/sdr/sdr-receivers.html 

In this session you will explore the radio frequency (RF) spectrum with one of these dongles (bring your own or use one provided) and open source software [https://www.rtl-sdr.com/big-list-rtl-sdr-supported-software/].  We'll look at the GNU Public Radio project, gqfx and some interesting uses folks have put these systems to, including pulling scientific data from satellites, hacking internet of things communications devices, and recording FM broadcasts.  For a project, by dragging and dropping filters, graphical controls, participabts will build a fully functioning FM tuner in a matter of minutes using GNU Public Radio.  Note that these devices are fully programmable in Python, making all kinds of interesting custom applications possible.

Check it out:
https://www.youtube.com/watch?v=mBU7eSviy_0
https://github.com/search?q=GNU+SDR

- **Where**: MADLab
- **When**: Thursday, March 14, from 18:10-19:00 pm
- **Instructor**: Brian 
- **Skill level**: Intermediate

*Installation instructions*: N/A. Equipment will be generously provided for this lesson by Brian.

*slides for this lesson here: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/misc/software-defined-radio/Information%20in%20the%20Air%20-%20SDR.pdf*

*Watch*: This event will be [streamed live](). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by linamnt** [comment]
We're holding this at MADLab this time!
