### ISSUE TITLE
Regression Models in R - March 21

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#228]
In this lesson, we learn to use regression models in R!

R is a powerful tool for doing simple to complex statistics, after all, that's what it was originally designed for. And, Regression is one of the primary tools in statistical modelling that allows us to examine the relationship between two or more variables of interest. So, no more to say, just come with RStudio installed and play.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, March 21, from 18:10-19:00 pm
- **Instructor**: Amin
- **Skill level**: Intermediate

*Installation instructions*: You will need to install the appropriate programs. See the R section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md). Please also install these packages: `install.packages(c('GGally', 'ggplot2', 'ppcor', 'openintro', 'stargazer', 'mctest', 'yhat', 'lmtest'))`.

~~*Watch*: This event will be [streamed live](). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)~~

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by QuLogic** [comment]
Sorry for our online viewers; we had a bit of a late start and were unable to setup the live stream today.

**Comment by QuLogic** [comment]
For those who were asking, the lesson plan was posted [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r/regression-models/20190321-regression-models.ipynb).
