### ISSUE TITLE
HTML and Web Design - March 28

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/Events#229]
- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, March 28, from 18:10-19:00 pm
- **Instructor**: TBA
- **Skill level**: Beginner

*Installation instructions*: 

GitHub Account
If you don't have one go to [github.com/join](https://github.com/join)
Git
Installation instructions and download links can be found on the [Git site](https://git-scm.com/downloads)
Jekyll

Installation instructions for can be found on the [Jekyll site](https://jekyllrb.com/docs/installation/)

*Watch*: This event will be [streamed live](). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by linamnt** [comment]
Here's a repost to the video that we're working through:
http://www.youtube.com/watch?v=oCCwtyH3SL4
