### ISSUE TITLE
Intro to Python - June 13

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/Events#238]
Intro to Python

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: June 13th from 18:10 to 19:00
**Instructor**: Lina @linamnt 
*Installation instructions*: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md).

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=xSOqFrrdQXw). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by aays** [comment]
@andrea1023 We're glad to hear that! No prior sign-up is needed - just show up to the MADLab in Gerstein Library at 6 pm on the day of the event and you'll be good to go.
