### ISSUE TITLE
Designing data analysis workflows - June 20

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/Events#239]
Systematic and reproducible management of your scientific workflow based on examples from electrophysiology or 'How to perform data analysis using snakes and elephants'

In this session I will introduce two tools which help in setting up reproducible scientific data analysis workflows: 

1. The workflow management system [*Snakemake*](https://snakemake.readthedocs.io) permits to define workflows in a pythonic, modular, human readable way using rules to define elemental processing steps. Snakemake workflows can be executed locally but also integrate well with distributed data and cluster computing.

2. The electrophysiology analysis toolkit [*Elephant*](http://neuralensemble.org/elephant) is an open-source package for the analysis of spiking as well as LFP activity. Elephant is based on the [*Neo*](https://neo.readthedocs.io/en/latest/)  framework, which provides a bridge to various different electrophysiology data formats and represents the data in a stardardized, annotated fashion.

**Where**: MADLab at [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx)
**When**: June 20th from 18:10 to 19:00
**Instructor**: Julia @JuliaSprenger
**Installation instructions**: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md).

To participate in the session, please set up a conda environment and install the required packages:

```
# setting up the environment
conda create -n demo python=3
conda activate demo

# installing required packages
conda install jupyter
conda install -c conda-forge bioconda::snakemake
conda install matplotlib
pip install nixio==1.5.0b3
pip install elephant
```

**Watch**: This event will be [streamed live](https://www.youtube.com/watch?v=FZKQgGt0vwg). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by JuliaSprenger** [comment]
Hi @margot-l!
I need to make some small changes in the requirements for the tutorial. Can you change the requirements to this?

```
# setting up the environment
conda create -n demo python=3
conda activate demo

# installing required packages
conda install jupyter
conda install -c conda-forge bioconda::snakemake
conda install matplotlib
pip install nixio==1.5.0b3
pip install elephant
```
Thanks!

**Comment by margot-l** [comment]
@JuliaSprenger Absolutely!
