### ISSUE TITLE
Unix Pipelines and Make

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#24]
James (@jamesaoverton) will lead a code-along based on the book [Data Science at the Command Line](http://datascienceatthecommandline.com) - learn about basic Unix pipelines to streamline your data analysis! This is a beginner-level code-along, so no prior command line experience is necessary.

**When:** December 10, 2015, 6:00 pm - 7:00 pm
**Where:** McLennan Physics building Rm. 408
**Preparation:** [Install Data Science Toolbox](http://datascienceatthecommandline.com/#dst)

**Comment by jamesaoverton** [comment]
The author of that book has created the [Data Science Toolbox](http://datasciencetoolbox.org), a virtual machine that you can install on Windows, Mac, or Linux. It's easier than it sounds! :^)

To get the most out of this session, follow steps 1 to 4 at the link below to install the Data Science Toolkit on your laptop. This involves some large downloads, so it would be better to install it **before** the session.

**Preparation:** http://datascienceatthecommandline.com/#dst

**Comment by jamesaoverton** [comment]
I've posted my slides on GitHub: https://github.com/jamesaoverton/command-line

If you [install the Data Science Toolbox](http://datascienceatthecommandline.com/#dst) before the session, then you can follow along with the examples. I'll try to arrive a little early and stay a little late to answer questions and help troubleshoot any problems.

See you tomorrow!
