### ISSUE TITLE
Journal Club - academic workflows - July 25

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/Events#255]
This week, we’re holding an open discussion on academic workflows; i.e. what has worked for you with regards to project management and organizing code/data/manuscripts and the like, any tips and tricks you’d like to share, and/or something specific about your workflow that you feel could be made more efficient and want to hear feedback about. Attendees are also welcome to connect their laptops to the projector for brief demos to the room.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, July 25, from 18:10-19:00 pm

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by linamnt** [comment]
https://raoofphysics.github.io/phd-starter-kit/#presentations--posters

**Comment by zackbatist** [comment]
https://github.com/zackbatist/open-SocSci

**Comment by aays** [comment]
Notes from today's session:

- 'four key stages' of research:
    - data collection
    - data analysis
    - data vis
    - writing/communicating work (talk/poster/paper)
- how do you deal with task management?
    - to do lists
        - Google Keep/Calendar
    - trello/asana - task boards
    - sticky notes/index cards - can also move them around to indicate progress
- data collection
    - how do you store and maintain data?
        - flash drives to store videos - sorted into days/contents
        - one drive is for 'raw', one is 'processed', one is used as a workspace
        - create backups as well
    - can sync computer w/ OneDrive/Google Drive/Dropbox
    - delete temp files - just keep raw and post-processed
    - common theme - having multiple places where 'multiple stages of data live'
- writing
    - Google Docs - but lack of a black background can be a problem!
    - markdown - many editors 
        - Zettlr - open source, still maintained, WYSIWYG, written by a sociologist specifically for academic writing
    - Pandoc - markdown to any output
    - VSCode - can be used for LaTeX (can preview equations) and do bib management (bibtex)
    - Overleaf - LaTeX - collaborative Google Docs-style writing
    - RStudio bookdown
- citation managers
    - Zotero
    - meitingtrunk (open source, modeled after Mendeley)
- other things
    - tmux! terminal multiplexer - allows you to run different bash sessions in the background + navigate b/w them
