### ISSUE TITLE
Machine learning: introduction to topics - August  8

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/Events#257]
Heard about machine learning? Curious about using it in your work or just want to know what all the fuss is about? In this tutorial you'll be introduced to the basics of machine learning. This tutorial will cover supervised machine learning. Specifically we'll dive into regression (e.g. Linear Regression) and Classification (e.g. SVM). We won't be covering other supervised or unsupervised algorithms (e.g. Neural Networks, Hierarchical Clustering), model selection (such as Bayesian Information Criteria - BIC) or hyper-parameter selection.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, August  8, from 18:10-19:00 pm
- **Instructor**: Haidy @HaidyGiratallah 
- **Skill level**: Intermediate

*Installation instructions*: You don't need to install anything for this lesson. We will be working on a hosted colab notebook follow directions from the following repo (https://github.com/HaidyGiratallah/Intro_to_Machine_Learning_2019)

In case you wish to run the notebook locally you will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-python-r.md). Please also install these packages: 

- seaborn
- matplotlib.pyplot
- pandas
- numpy
- sklearn

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=33g5Se0ZD1g). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by aays** [comment]
Update: the livestream is [here](https://www.youtube.com/watch?v=33g5Se0ZD1g)! Apologies for the mix-up - we had to switch to a different livestreaming software this week.
