### ISSUE TITLE
Intro to Ruby

### ISSUE THREAD

**Issue by jennaleeb** [UofTCoders/Events#26]
This is a very basic beginner-friendly introduction to the Ruby programming language. 

**When:** Thursday, January 14, 2016, 6pm - 7pm
**Where:** MP 408 (Mclennan Physical Labs in the Burton Tower)
**Preparation:**

1. Install Ruby

* *Mac Users:*
Ruby is already on your computer. It comes with it! You just need to make sure you can open the application "Terminal". Go to Applications > Utilities > Terminal.

* *Windows Users:*
(if you are on your work computer, you may have to ask IT at work if you don't have administrator privileges)
Go to http://rubyinstaller.org
Click the "DOWNLOAD" button
Click the link 'Ruby 2.0.0-p247' (or the most recent version) under RubyInstallers and save the file to 
 your desktop
Once the file has finished downloading, double-click on rubyinstaller-2.0.0-p247.exe
Once setup is running, click 'I accept the License'
Click 'Next'
Do not change the default install directory, C:\Ruby202
Tick 'Add Ruby executables to your PATH'
Tick 'Associate .rb and .rbw files with this Ruby installation'
DO NOT tick "Install Tcl/Tk support"
Click 'Install'
Click 'Finish' when you see the completion window
If you run into trouble with these instructions, don't worry! Just arrive a few minutes early on Saturday (anytime after 9:15 am) and one of our amazing developer volunteers will help you out.

2. Download a good text editor: Sublime Text www.sublimetext.com

3. (Optional) Download the slides here https://github.com/jennaleeb/ruby_workshop

**Comment by lwjohnst86** [comment]
Any love for the Linux users??

For Linux users, you can use the [Ruby doc website](https://www.ruby-lang.org/en/documentation/installation/). Should be as easy as:
```
sudo apt-get install ruby-full
```

Though the versions on the package repositories may be out of date. @jennaleeb what version should we be installing? Ubuntu's version is 1.9.3. Is that fine?

**Comment by jennaleeb** [comment]
Yes that should be fine! We're mostly looking at basic programming concepts (data types, variables, conditional logic) using the Interactive Ruby Shell and running short programs.
