### ISSUE TITLE
Python Unit Tests - November  7

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/Events#267]
Want to be sure your code works as intended? Say hello to unit testing! Unit tests are an automated way to check your code for bugs. Not only that but developing unit tests will improve your code all on its own.

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, November  7, from 18:10-19:00 pm
- **Instructor**: James (@James-S-Santangelo)
- **Skill level**: Intermediate

*Installation instructions*: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-python-r.md). Please also install these packages: numpy, unittest, gc.

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=TRjfVDe7OLQ). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by jessexknight** [comment]
Unfortunately, I won't be able to make this event. But I do have a decent "hello world" project which illustrates some examples of python unit testing using [pytest](http://doc.pytest.org). Feel free to use as an example and / or share with attendees it's useful:

https://github.com/jessexknight/ndna

**Comment by aays** [comment]
@jessexknight Bummed you can't make it, but thanks for sharing the link Jesse!
