### ISSUE TITLE
Intro to Statistics in Python - November 14

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/Events#268]
Statistics is an important cornerstone to data analysis. Our introduction to doing statistics in Python lesson will go over basic descriptive and inferential statistics

- **Where**: [MADLab](https://goo.gl/maps/cfygtx94KL92)
- **When**: Thursday, November 14, from 18:10-19:00 pm
- **Instructor**: Raul (@ralle123)
- **Skill level**: Intermediate

*Installation instructions*: You will need to install the appropriate programs. See the Python section of the [installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md). Please also install these packages: scipy.stats.

*Watch*: This event will be [streamed live](https://www.youtube.com/watch?v=wd70pP90ikg). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

**Directions:**  MADLab is located in [Gerstein Science Information Centre](https://goo.gl/maps/2916Y54jQkx), Room B112 at the south end of the first lower level. Once you go through the main entrance of Gerstein, take a right turn down a corridor (across from the admin desk or just past the reading room), then take the stairs down and follow the signs to MADLab, the door should be open 10-15 minutes before the lesson.

**Comment by HaidyGiratallah** [comment]
Here are the files used for this lesson:

[marathon_results_2015_version2.csv.zip](https://github.com/UofTCoders/Events/files/3849167/marathon_results_2015_version2.csv.zip)

**Comment by HaidyGiratallah** [comment]
Here's the Jupyter Notebook for this lesson:

[intro to stats in python.zip](https://github.com/UofTCoders/Events/files/3849230/intro.to.stats.in.python.zip)
