### ISSUE TITLE
The 'Class' Structure in Python

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#28]
Here we will touch on the concepts of object-oriented programming and dive into creating and using classes in Python.

**When**: Thursday, January 21, 2016, 6pm - 7pm
**Where**: MP 408 (Mclennan Physical Labs in the Burton Tower)

**What You Will Need**:

Python 2.7, or 3.4+ installed
Download the [files](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/pythonClasses) for this lesson
If you'd like to follow along in IPython Notebook, do the following:
1. Install Jupyter Notebook
2. Run the notebook by typing `jupyter notebook` into command line.
3. In the web application that opens, navigate to the folder containing the files you downloaded, and open 'Classes in Python.ipynb' to follow along.

Otherwise, you can follow along in your favourite IDE or command line.

All the code will be posted to "Classes in Python", and as a .py file after the lesson.

**Comment by lwjohnst86** [comment]
Excellent job Lina!

**Comment by tkivisik** [comment]
Thanks Lina.
