### ISSUE TITLE
Lightning Demos: Python - November 5

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#288]
What's something cool you've done in Python recently? Any useful package or trick you've found or learned about? Come by and either present something or sit back and watch others' demos! 

There are no rules with Lightning Demos besides demos being no more than 5-10 minutes in length and focusing primarily on the code itself. Anyone is welcome to present! 

**Where**: Zoom (Meeting ID: 861 0071 5008, password: coders - link [here](https://utoronto.zoom.us/j/86100715008))
**When**: Thursday, November 5, from 19:00 - 20:00
**Instructor**: n/a
**Skill level**: n/a

_Installation Instructions_: n/a

**Note**: Our sessions will all be held online until further notice, instead of at the MADLab.

**Comment by jessexknight** [comment]
Hey @aays!
I might not be able to attend, but wanted to share some fitting python "gists", in case you'd like to share somehow on Thurs:

- [super simple web server](https://gist.github.com/jessexknight/20e20a91e0e6dc0761fffe7ac53e0ebd)
- [recursive reliably flatten nested lists](https://gist.github.com/jessexknight/0314ffeec4ff39e350976f9cbc0f372c)
- [decorator to make a gif from any plot function](https://gist.github.com/jessexknight/6a32a49f5ddf6ba42093a48d22cccbb4)

**Comment by jessexknight** [comment]
Example output from the gif-maker, since it's not in the gist:

![radar](https://user-images.githubusercontent.com/14393754/97948299-2338fa00-1d5e-11eb-957f-8174b239492d.gif)

**Comment by aays** [comment]
@jessexknight Awesome stuff! Will definitely try to share these if you're not able to make it!

**Comment by aays** [comment]
Some things that were covered past the above list:

- [virtualenv](https://docs.python.org/3/library/venv.html) and [conda env](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html) for management of different Python versions
- creating reproducible workflows with [snakemake](https://snakemake.readthedocs.io/en/stable/) 
- [ptpython](https://github.com/prompt-toolkit/ptpython), a feature rich Python REPL/interactive interpreter

Thanks all for a great session!

**Comment by QuLogic** [comment]
Also mentioned:
* [direnv](https://direnv.net/) (not Python, but useful for auto-activating environments)
*  `python3 -m http.server` for an even simpler HTTP server

**Comment by jessexknight** [comment]
Thanks @QuLogic!

You reminded me, the reason I made the [web server script](https://gist.github.com/jessexknight/20e20a91e0e6dc0761fffe7ac53e0ebd) vs your solution is: to force the server to assume the default file extension is `.html`, since the links on my site omit the extension so that the URLs are pretty. Most production servers (e.g. [GitHub Pages](https://pages.github.com/)) will happily load `index.html` given the URL `index`, but `python3 -m http.server` will not, complaining that `index` does not exist.
