### ISSUE TITLE
Scientific Writing with Markdown and Pandoc - November 26

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#291]
An introduction to writing scientific and technical documents with Markdown and managing document formats with Pandoc. 

**Where**: Zoom (https://utoronto.zoom.us/j/86100715008 (Password: coders))
**When**: Thursday, November 26, from 19:00 - 20:00
**Instructor**: Frances (@FrancesWong)
**Skill level**: Beginner to intermediate

_Installation Instructions_: Pandoc installed as well as LaTeX. For more details see [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/misc/pandoc-intro/lesson.md#getting-started). Pandoc version 2.0+ is preferred but not required.

**Note**: Our sessions will all be held online until further notice, instead of at the MADLab. **If you need help with installation, please be sure to show up at 18:50 (6:50 pm) so that we can help you out before the lesson!**

**Comment by FrancesWong** [comment]
Hi! 

Some resources that we'll be using for the lesson: 

Online markdown editor: https://dillinger.io/

Text for bib file: 
`
@article{johnston2019,
    title = {A graduate student-led participatory live-coding quantitative methods course in {R}: {Experiences} on initiating, developing, and teaching},
    volume = {2},
    issn = {2577-3569},
    shorttitle = {A graduate student-led participatory live-coding quantitative methods course in {R}},
    url = {https://jose.theoj.org/papers/10.21105/jose.00049},
    doi = {10.21105/jose.00049},
    language = {en},
    number = {16},
    urldate = {2020-11-23},
    journal = {Journal of Open Source Education},
    author = {Johnston, Luke and Bonsma-Fisher, Madeleine and Ostblom, Joel and Hasan, Ahmed and Santangelo, James and Coome, Lindsay and Tran, Lina and De Andrade, Elliott and Mahallati, Sara},
    month = jun,
    year = {2019},
    pages = {49},
    file = {Johnston et al. - 2019 - A graduate student-led participatory live-coding q.pdf:C\:\\Users\\Frances\\Zotero\\storage\\9DEBU765\\Johnston et al. - 2019 - A graduate student-led participatory live-coding q.pdf:application/pdf}
}`

Script for wordcount: https://github.com/pandoc/lua-filters/blob/master/wordcount/wordcount.lua

File for pdf template: https://github.com/Wandmalfarbe/pandoc-latex-template
