### ISSUE TITLE
Lightning Demos: Data visualization - December 3

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#292]
Come share some cool plots you've made and how you made them! All languages and fields of research welcome.

There are no rules to Lightning Demos except that demos should be no more than 5-10 minutes in length and focusing primarily on the code itself. Anyone is welcome to present!

**Where**: Zoom https://utoronto.zoom.us/j/86100715008 (Password: coders)
**When**: Thursday, December 3, from 19:00 - 20:00
**Instructor**: n/a
**Skill level**: n/a

_Installation Instructions_: n/a

**Note**: Our sessions will all be held online until further notice, instead of at the MADLab.

**Comment by margot-l** [comment]
Network of genes/metabolites in R: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2682514/ The The R significance brackets (using the manual entry): https://github.com/const-ae/ggsignif 
From Me to Everyone: (8:06 PM)
A great tutorial on both numpy and pandas (Python) and how to use them together: https://www.hackerearth.com/practice/machine-learning/data-manipulation-visualisation-r-python/tutorial-data-manipulation-numpy-pandas-python/tutorial/

**Comment by aays** [comment]
Other things that were covered:

- assembling plots with [patchwork](https://patchwork.data-imaginist.com/) (again!) 
- making plots of maps with Tableau
- making pretty heatmaps in R with [`pheatmap`](https://rdrr.io/bioc/TRONCO/man/pheatmap.html)
- using the [projects](https://cran.r-project.org/web/packages/projects/index.html) package to streamline making plots and overall project management
- using functions with ggplot themes + using lists to save ggplot theme formatting:

```R
# use function to make a modifiable theme object
fig_1_theme <- function(font_size = 12) {
  theme(
    axis.title = element_text(family = 'Helvetica', size = font_size,
    axis.text = element_text(family = 'Helvetica', size = font_size))
  }
}

# save ggplot plot modifications to list
plot_mods <- list(
  xlab('Length'),
  ylab('Width'),
  coord_cartesian(x = c(0, 10), y = c(0, 10)
)

sepal_plot <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width) +
  geom_point() +
  fig_1_theme(font_size = 12) +
  plot_mods

petal_plot <- ggplot(iris, aes(x = Petal.Length, y = Petal.Width) +
  geom_point() +
  fig_1_theme(font_size = 12) +
  plot_mods

# join plots with patchwork
final_plot <- sepal_plot + petal_plot + plot_layout(ncol = 1, nrow = 2)
```

Thanks all for a great session and a wonderful semester! We hope to have a schedule out for next semester's events soon. We also aim to send out a survey to help gauge interest in different event topics for the coming semester - stay tuned!
