### ISSUE TITLE
Introduction to R - January 20

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#294]
The basics of using R and the Tidyverse for working with data, specifically:
- Intro to R/navigating RStudio
- Intro to Tidyverse
- pipe operators
- Basic data wrangling with dplyr and tidyr packages

**Where**: Zoom (link [here](https://utoronto.zoom.us/j/83940578226) - pass is 'coders' without the quotes)
**Meeting ID**: 839 4057 8226
**When**: Wednesday, January 20, from 18:00 - 19:00
**Instructor**: Margot (@margot-l)
**Host**: TBA
**Skill level**: Beginner

_Installation Instructions_:  You will need to install the appropriate programs. See the [R section of the installation instructions page](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md#installing-r). Please also install these packages: dplyr, tidyr.

_Lesson material_: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r/intro/Intro_to_R_May23.Rmd

Note: Our sessions will all be held online until further notice, instead of at the MADLab. **If you need help with installation, please be sure to show up at 17:50 (5:50 pm) so that we can help you out before the lesson!**

**Comment by jennifer-allott** [comment]
I might just be missing it, but I don't see the zoom link anywhere :)

**Comment by SandhyaMylabathula** [comment]
I also don't see the Zoom link :(
