### ISSUE TITLE
Python: scikit-learn - February 3

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#296]
This lesson will introduce you to classification and machine learning using the powerful tools from the scikit-learn package.

**Where**: Zoom 
**Meeting ID**: TBA
**When**:  -- Cancelled -- 
**Instructor**: @HaidyGiratallah 
**Host**: TBA
**Skill level**: Intermediate

_Installation Instructions_: For this lesson, if you'd like to code along, please install Python following the instructions [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md#installing-git). You will also need to install the scikit-learn package.

_Lesson material_: TBA

Note: Our sessions will all be held online until further notice, instead of at the MADLab. **If you need help with installation, please be sure to show up at 17:50 (5:50 pm) so that we can help you out before the lesson!**

**Comment by FrancesWong** [comment]
Hi everyone,

We need to cancel this evening’s lesson, sorry about that. We’ll offer it next semester. We do have several past lessons on our GitHub which you can check out. https://uoftcoders.github.io/studyGroup/lessons/python/scikit-learn/lesson/

In the meantime if you’re missing your weekly Coders time, on Thursday at 1pm as ever, we have our co-working session hosted on our discord (https://discord.gg/UWQGsmyz). Come work in code or any other project for the whole hour or drop in. You’ll need to sign in to the discord and then look under Voice Channels for Co-working. If you have any questions, don’t hesitate to ask. We normally start of by saying what we hope to get done and if anyone gets stuck or has a question, we encourage it and we can help.

Cheers,
UofT Coders
