### ISSUE TITLE
R: Statistical methods - February 10

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#297]
This lesson will work you through a classic statistical problem that you can solve in R and includes visualization methods as well as regression analysis.

**Where**: Zoom (link https://utoronto.zoom.us/j/83940578226 (Passcode: coders))
**Meeting ID**: TBA
**When**: Wednesday, February 10, from 18:00 - 19:00
**Instructor**: Amin (@ab2347) 
**Host**: TBA
**Skill level**: Intermediate

_Installation Instructions_: For this lesson, if you'd like to code along, please install R following the instructions here. You will also need to install here, tidyverse, openintro, naniar, table1, GGally, numform, car, and report. 

report gets installed like so 
```
install.packages("remotes")
remotes::install_github("easystats/report")
```

_Lesson material_: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r/regression-models/regression_lesson.zip

Note: Our sessions will all be held online until further notice, instead of at the MADLab. **If you need help with installation, please be sure to show up at 17:50 (5:50 pm) so that we can help you out before the lesson!**

**Comment by itamar121** [comment]
Not sure what #297 means
also how to read this repo ?
cheers
Itamar

**Comment by FrancesWong** [comment]
The number is a numeric index for the issue number. 

This repo, /Events, is to centralize information about our events. Information about the event and relevant links are found in the first comment. 

Please refrain from commenting on closed issues on GitHub, they are generally not maintained -thanks!
