### ISSUE TITLE
Intro to Python

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#3]
The very basics of the programming language Python. @cczhu will lead a beginner-friendly code-along.

**When:** Thursday, July 9, 2015, 6pm - 7pm
**Where:** MP 408 (Mclennan Physical Labs in the Burton Tower)
**Preparation:** 
- Download Python (either [2](https://www.python.org/downloads/release/python-2710/) or [3](https://www.python.org/downloads/release/python-343/)). If you're on Mac or Linux, you probably already have Python installed. If this is the first time you're installing Python, I strongly recommend downloading and installing [Anaconda](http://continuum.io/downloads) which includes Python, IPython, sympy, numpy, and many other useful packages. It'll save you installing a bunch of common packages right away. 
- Recommended: install [IPython](http://ipython.org/install.html) (if you're not going the Anaconda route)
- Optional: Download and install a development environment (I use [WingIDE101](http://www.wingware.com/downloads/wingide-101/5.1.5-1))

**Comment by QuLogic** [comment]
It's IPython; it's not an Apple product.

**Comment by QuLogic** [comment]
@cczhu Are you planning to post anything before the tutorial?

**Comment by cczhu** [comment]
Yes, I just sent a pull request to the studyGroup repo with the handouts.
