### ISSUE TITLE
Co-working - Thursdays at 1 pm from Jan - March! 

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#302]
An informal co-working session over Discord, hosted by @margot-l. Come hang out with us while working on code or whatever else you'd like to get done! 

**Where**: UofT Coders Discord Server (link https://discord.gg/ud984rW9vK)
**Discord Channel**: Voice channels -> Co-working
**When**: Every Thursday (from Jan 14 to Mar 18), from 13:00 - 14:00
**Host**: @margot-l

**Comment by PhilipeRLeal** [comment]
Dear margot-l, would you be so kind to provide a preview of the main topics of this Co-Working assignment?

Sincerely,

**Comment by margot-l** [comment]
@PhilipeRLeal 
There isn't any assignment, you just bring whatever project you're working on. We talk at the beginning about what our goals are for the day and if anyone has a question they'd like some help on, they ask in the voice chat with screen sharing if needed.

**Comment by PhilipeRLeal** [comment]
Dear Margot Lautens,

thank you for your reply.

At the present moment, I don't believe that I have some major Issue to
discuss within the group.

Therefore, I will just follow the other group members, and what they may
bring.


Sincerely,

Philipe Riskalla Leal,
Sensoriamento Remoto - INPE


Em ter., 26 de jan. de 2021 às 20:24, Margot Lautens <
notifications@github.com> escreveu:

**Comment by PhilipeRLeal** [comment]
Dear all,

 I would like to raise a personal Issue regarding the interoperability between pandas and SQL.

If you all consider that as being a valid topic, let me know.

Sincerely,
