### ISSUE TITLE
UofT Coders Elections - May 17th

### ISSUE THREAD

**Issue by aays** [UofTCoders/Events#333]
Hello all,

Interested in getting involved with UofT Coders? Excited about sharing programming skills for research? We will be holding elections for our executive positions this **Wednesday, May 17, 2023**. Everyone is welcome to nominate themselves for a position, though nominees for President must have attended at least 5 meetings. Please see below for further details about the nomination process.

The elections will be held on our [Discord](https://discord.com/invite/ud984rW9vK) at 6 pm, with voting taking place directly on Discord using a poll bot once nominations are in. The roles up for election are:

    President (must have previously been to at least 5 meetings, either attending or leading a session)
    Technical Admin
    Admin
    Treasurer
    Marketing Coordinator

Descriptions of these roles can be found [here](https://github.com/UofTCoders/council/blob/master/Council_Roles.md). If you have ideas for a role that is not currently covered by one of these positions, please let us know via email! (more below)

---

### Nomination Process

If you’d like to nominate someone or yourself for a position, please be sure to email uoftcoders@gmail.com before May 16th with the following:

- Name
- Department/Affiliation
- Which executive position you’d like to run for
- Why you’d like to take on this role

Nominees are also expected to present a short speech introducing themselves and their interest in a given role on election night. If you are unable to make it on the evening of the 17th but are still interested, please also include any statement past the listed points above in your email and we will read it out in your absence.

Finally, once again if you have ideas for a role that is not currently covered by one of our existing positions, please let us know at the same email listed above.

Whether you are running or not, make sure you come out to vote! Hope to see you there!

**Where**: [Discord](https://discord.com/invite/ud984rW9vK)
**When**: May 17, 2023
**What to bring**: Yourself!

**Comment by QuLogic** [comment]
This happened already.
