### ISSUE TITLE
Introduction to R (5:30 PM, Nov 8)

### ISSUE THREAD

**Issue by vickimzhang** [UofTCoders/Events#335]
This is a very basic introduction to the R programming language with a particular focus on the dplyr and ggplot packages. Instead of covering more advanced statistical methods, this lesson aims to provide an understanding of fundamental data manipulation and visualization operations in R.

The lesson covers the R/RStudio interface and R Notebooks, objects and functions, data frames, the dplyr package, reading and writing files in R, introductory plotting with ggplot2, and knitting Rmd files.

[**Register here**](https://www.utm.utoronto.ca/asc/graduate-students/workshops-graduate-students)
**Where**: Collaborative Digital Research Space (MN3230) and livestreamed on the UofT Coders [Discord](https://discord.gg/Aj4a4Sua)
**When**: 5:30-7:30 PM, November 8
**Instructor**: Sophie (@sbreitbart) 
**Level**: Beginner

Installation instructions: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/install-git-python-r.md#installing-r

**Comment by sbreitbart** [comment]
On the RGASC website, this event is scheduled for 6-8pm on that Monday (Nov
6)

**Comment by vickimzhang** [comment]
@sbreitbart updated! I know it's virtual but is it also being broadcasted from the RGASC computer room in MN?

**Comment by sbreitbart** [comment]
Yes. Thanks!
