### ISSUE TITLE
Code review and reproducible computational research

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#36]
People are talking a lot these days about research being "open" and "reproducible". It all sounds great, but HOW do we do it? How can we apply these great ideals to our actual work?

This week we'll discuss reproducible computational research, guided by [Ten simple rules for computational research](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285) and Mozilla's [code review guidelines](http://mozillascience.github.io/codeReview/review.html), and then we'll review each other's analysis scripts to see how they conform to these guidelines and if they can be improved. 

I'll be honest, this is an intimidating topic, but we will do everything possible to make this intro as un-scary as possible. This means that my code will be the first up for review, and I can guarantee that my code is not a shining beacon of reproducible perfection. This also means that if you want to come and only observe, that's great! If you want to come and discuss, but don't want to get into the reviewing part, that's great too. It doesn't matter what stage of programming or research you're at. Also, I've never done this before and as a group we've never done this before, so we can all bumble along together, which, after all, is the point of UofT Coders!

Lastly, we will be relying on our [Code of Conduct](https://github.com/UofTCoders/studyGroup/blob/gh-pages/codeOfConduct.md) heavily - we want this to be a welcoming environment for absolutely everyone. So bring your friends!

**When:**  6:10 pm - 7:30 pm on March 17, 2016
**Where:** MP 408 - Mclennan Physical Labs, Burton Tower
**Preparation:** (Optional) Read the article [Ten simple rules for computational research](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285), and check out Mozilla Science Lab's [code review guidelines](http://mozillascience.github.io/codeReview/review.html).

**Comment by emilymae** [comment]
Meant to bring this up yesterday, you want another _Ten simple rules,_ there's a kind of complementary article about data (more about sharing and access than reproducibility): [Ten Simple Rules for the Care and Feeding of Scientific Data](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003542)

**Comment by dcwalk** [comment]
@emilymae thanks! definitely wanted the link.
