### ISSUE TITLE
Using branches in Git

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/Events#39]
Heard about git branches but don't really understand what they do and why to use them? Come to this code-along session to learn about how, why, and when to use branches! No prior Git experience is necessary, all are welcome.

**When:** Thursday, March 31, 6 pm - 7 pm
**Where:** MP 408 ([Mclennan Physical Labs](https://www.google.ca/maps?q=mclennan+physical+labs&es_sm=122&um=1&ie=UTF-8&sa=X&ved=0CAcQ_AUoAWoVChMIoI3D7v-RxgIViEySCh34tAQ3), in the Burton tower)
**What to bring:** Computer, charged if possible, with Git installed (instructions below).

### Git ###

Installation instructions for Git can be found on the
[Git download site](http://git-scm.com/book/en/Getting-Started-Installing-Git)

* On Windows: Download the `.exe` file from this
  [Github link](http://msysgit.github.io) and run it.

* On Mac: To use the graphical Git installer, download from this
  [SourceForge link](http://sourceforge.net/projects/git-osx-installer/)

* On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by mbonsma** [comment]
We'll be broadcasting this event live via Google Hangouts. Click [here](http://www.youtube.com/watch?v=nRUW6LLkCqQ) to watch the YouTube stream, assuming everything works!

**Comment by QuLogic** [comment]
Congratulations on being the first one broadcast @lwjohnst86!

**Comment by lwjohnst86** [comment]
Thanks! Now we know how to do it, so gotta get more going! :stuck_out_tongue:
