### ISSUE TITLE
Introduction to R via data wrangling and reproducible documents

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/Events#4]
A brief introduction to the uses of R for data wrangling and creating
reproducible documents.  R's strength comes from it being developed by
statisticians for doing data analysis.  The goal of this session is to
go over the basics to getting your data into an analyzable format
(data wrangling) and producing a document of the results.

* **When**: Thursday, July 23rd, 2015, 6:00-7:00pm
* **Where**: MP 408 (Mclennan Physical Labs in the Burton Tower)

**Preparation**:

Install:

* [R](https://cran.rstudio.com/)
* [RStudio](https://www.rstudio.com/products/rstudio/#Desktop)

Because internet is sporatic in MP408, please *come to the session*
with `dplyr`, `tidyr`, and `rmarkdown` (this one may already be
installed) packages **installed** either by using the RStudio
**"Tools->Install packages"** option or by typing these commands into
the R console:

    install.packages('dplyr')
    install.packages('tidyr')
    install.packages('rmarkdown') ## This one may already be installed..

**Comment by QuLogic** [comment]
Here's the link to the merged information: http://uoftcoders.github.io/studyGroup/lessons/introR/main.html

**Comment by lwjohnst86** [comment]
I've submitted a pull request to include the practice task you can try out using the session material (https://github.com/UofTCoders/studyGroup/pull/29).

I also mentioned about running through multiple combinations of y and x of a linear regression, [here is the blog post](http://sciencestatisticsandlife.com/loops-forests-multiple-linear-regressions/) I wrote up about it. So try it out! Those that have used R before may really appreciate the simplicity of using dplyr for this type of task! :)

Thanks everyone for coming out!
