### ISSUE TITLE
Web design with Jekyll/GitHub Pages

### ISSUE THREAD

**Issue by dcwalk** [UofTCoders/Events#42]
Curious about [GitHub Pages](https://pages.github.com/) to host a web page? Github Pages allow users to host websites for free right from their repository using [Jekyll](https://jekyllrb.com/) and plain HTML content!

Come code-along to learn more. No prior experience with GitHub, HTML or Jekyll is necessary, all are welcome. We will be trying out a few different tools so make sure to check the installation instructions!

**When:** Thursday, April 14, 6 pm - 7 pm
**Where:** MP 408 (Mclennan Physical Labs, in the Burton tower)
**What to bring:** Computer, charged if possible, with a GitHub account, Git installed and if possible Jekyll installed too (instructions below)

### GitHub Account
If you don't have one go to [github.com/join](https://github.com/join)

### Git
[Installation instructions](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) and [download links](https://git-scm.com/downloads) can be found on the Git site

### Jekyll
[Installation instructions](https://jekyllrb.com/docs/installation/) for  can be found on the Jekyll site

Unfortunately Windows is not officially supported, however there are instructions for [Jekyll on Windows](https://jekyllrb.com/docs/windows/#installation). We are only going to briefly touch on using Jekyll from the command line at the end, so no worries if you don't have it working!

**Comment by mbonsma** [comment]
Watch the live stream [here](http://www.youtube.com/watch?v=44xoR-EqT_g)!

**Comment by joelostblom** [comment]
Thanks for this lecture and for making the stream available! I couldn't attend the session, but I just watched it and it was really helpful in getting started.
