### ISSUE TITLE
Intro to Pandas in Python - April 28

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#45]
Learn the basics of using the Pandas package in Python for dealing with data structures and analysis. 

**Where**: MP408
**When**: Thursday, April 28, 6pm - 7pm
**What to bring**: A laptop with a [Python installation](https://www.python.org/downloads/) as well as the [Pandas package](http://pandas.pydata.org/pandas-docs/stable/install.html)

More information to come!

**Comment by derekhoward** [comment]
The presentation will be done in a Jupyter notebook and will make use of some of the plotting functions in [seaborn](https://stanford.edu/~mwaskom/software/seaborn/).

Python installation with Jupyter notebook can be simplified with [Anaconda](https://www.continuum.io/downloads). 

After python is setup, **conda install seaborn** should take care of installation of seaborn and it's dependencies.

**Comment by mbonsma** [comment]
The presentation will be live-streamed [here](http://youtu.be/SihxkCtRPBs)!

**Comment by mbonsma** [comment]
Here is the lesson for reference: https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/pandas_walkthrough
