### ISSUE TITLE
An Intro to the Use and Philosophy of Version Control - May 19

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#47]
Learn how to take advantage of version control for your projects why it can be useful. We will be focusing on Git, a popular piece of software that does version control. This session is geared towards complete beginners - if you've never touched Git before, this is for you!

**Where**: MP408
**When**: Thursday, May 19, 6-7pm
**Preparation**: Bring a laptop with Git installed (see instructions below). Optional: make an account on [GitHub](https://github.com/join?source=header-home). It's free! 

### Git ###

Installation instructions for Git can be found on the [Git download site](https://git-scm.com/book/en/Getting-Started-Installing-Git)

* On Windows: Download the `.exe` file from this
  [Github link](https://msysgit.github.io) and run it.

* On Mac: To use the graphical Git installer, download from this
  [SourceForge link](https://sourceforge.net/projects/git-osx-installer/)

* On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by mbonsma** [comment]
The event will be live-streamed [here](http://www.youtube.com/watch?v=1xeVRpl-lFU)!

**Comment by JoshuaFolly** [comment]
Thank you
