### ISSUE TITLE
Introduction to R - May 26

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#49]
A brief introduction to the uses of R for data analysis and data wrangling. 

**Where**: MP408
**When**: Thursday, May 26, 6-7pm
**What to bring**: A laptop with [R](https://cran.rstudio.com/) and [RStudio](https://www.rstudio.com/products/rstudio/#Desktop) installed

More information to come!

**Comment by Lizzymae2** [comment]
How can I sign up? (Sorry, newbie here)

**Comment by linamnt** [comment]
Hi @Lizzymae2, welcome! There is no need to sign up for our weekly meetings, you can just show up May 26 at 6pm and we'd be happy to have you!

**Comment by lwjohnst86** [comment]
Just so others can see it, the session was recorded and is available [here](https://www.youtube.com/watch?v=pbG_3ZuNyx8)
