### ISSUE TITLE
Introduction to Python - June 9

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#51]
The very basics of the programming language Python with a beginner-friendly code-along. 

**Where**: MP408
**When**: Thursday, June 9, 6-7pm
**Preparation**: 
Download Python ([preferably 3, but 2 is also fine](https://www.python.org/downloads/)). If you're on Mac or Linux, you probably already have Python installed. [Anaconda](https://continuum.io/downloads) which includes Python, IPython, NumPy, and many other useful packages is highly recommended if you do not yet have Python. 

More information to come!

**Comment by sina-sed** [comment]
Hi everyone, 

Please download the attached .zip file in preparation for the lesson today. See you all soon!

Best,
Sina

[Intro_Python.zip](https://github.com/UofTCoders/Events/files/307872/Intro_Python.zip)

**Comment by mbonsma** [comment]
Today's code along will be live-streamed [here](http://youtu.be/KXSyN9HAbi0).
