### ISSUE TITLE
Software Carpentry Workshop - Python, Unix Shell and Git (May 26-27) for people who identify as female

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#52]
U of T Scientific Coders is organizing a hands-on two-day Software Carpentry workshop that covers the core skills needed to be productive in a small research team.

**Note: To support and encourage gender minorities in the world of programming, this workshop is open only to those who identify as female.**

Through short tutorials alternating with practical exercises, attendees will learn:

Programming with **R**
Automating tasks with the Unix Shell
Version control with Git
More information and **registration** can be found on the event website: https://uoftcoders.github.io/2016-05-26-utoronto/

You don't need to have any previous knowledge of the tools that will be presented at the workshop.

Cost: $20, [registration required](https://uoftcoders.github.io/2016-05-26-utoronto/)
When: May 26-27, 2016, 9:00 am - 4:00 pm
Who: The course is aimed at undergraduate student researchers, graduate students, and other researchers from the University of Toronto
Where: Claude T. Bissell Building, 140 St. George St., Room BL224/225
Preparation: Instructions can be found on the event website: https://uoftcoders.github.io/2016-05-26-utoronto/
Requirements: Participants must bring a laptop with a Mac, Linux, or Windows operating system (not a tablet, Chromebook, etc.) that they have administrative privileges on.

_Please Note: this event has a [Code of Conduct](https://software-carpentry.org/conduct/)._

**Comment by nattha-wannissorn** [comment]
Hey Madeleine,
When I saw the event on Github, I was looking for a way to register and
couldn't find it. Now that Lina just sent out an email (11 minutes after I
got the email), it's full and I could only sign up for the waitlist. I
guess since people paid for the registration, they are unlikely to cancel.
You may want to consider adding some more capacity btw.

Hoping to attend on the 26th. :D

Nattha

On Mon, May 9, 2016 at 4:00 PM, Lina Tran <notifications@github.com> wrote:

> U of T Scientific Coders is organizing a hands-on two-day Software
> Carpentry workshop that covers the core skills needed to be productive in a
> small research team.
>
> *Note: To support and encourage gender minorities in the world of
> programming, this workshop is open only to those who identify as female.*
>
> Through short tutorials alternating with practical exercises, attendees
> will learn:
>
> Programming with *R*
> Automating tasks with the Unix Shell
> Version control with Git
> More information and *registration* can be found on the event website:
> http://uoftcoders.github.io/2016-05-26-utoronto/
>
> You don't need to have any previous knowledge of the tools that will be
> presented at the workshop.
>
> Cost: $20, registration required
> <http://uoftcoders.github.io/2016-05-26-utoronto/>
> When: May 26-27, 2016, 9:00 am - 4:00 pm
> Who: The course is aimed at undergraduate student researchers, graduate
> students, and other researchers from the University of Toronto
> Where: Claude T. Bissell Building, 140 St. George St., Room BL224/225
> Preparation: Instructions can be found on the event website:
> http://uoftcoders.github.io/2016-05-26-utoronto/
> Requirements: Participants must bring a laptop with a Mac, Linux, or
> Windows operating system (not a tablet, Chromebook, etc.) that they have
> administrative privileges on.
>
> *Please Note: this event has a Code of Conduct
> <http://software-carpentry.org/conduct/>.*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UofTCoders/Events/issues/52>
>



-- 
Nattha Wannissorn
PhD Student
Department of Molecular Genetics
University of Toronto & Donnelly Centre
Laboratory of Dr. Andrew Fraser
160 College St
Toronto ON
M5S3E1

**Comment by QuLogic** [comment]
@nattha-wannissorn I'm not sure if you saw this or not, but there are still a few free tickets at the moment.

**Comment by nattha-wannissorn** [comment]
@Elliot I paid lol. Is it supposed to be free for me?

On Thu, May 19, 2016 at 4:46 PM, Elliott Sales de Andrade <
notifications@github.com> wrote:

> @nattha-wannissorn <https://github.com/nattha-wannissorn> I'm not sure if
> you saw this or not, but there are still a few free tickets at the moment.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UofTCoders/Events/issues/52#issuecomment-220442931>
>



-- 
Nattha Wannissorn
PhD Student
Department of Molecular Genetics
University of Toronto & Donnelly Centre
Laboratory of Dr. Andrew Fraser
160 College St
Toronto ON
M5S3E1

**Comment by QuLogic** [comment]
Weird, I don't know why I didn't receive a notification earlier. Anyway, I meant free as in "not taken", not "without charge".

**Comment by nattha-wannissorn** [comment]
I see. It was worth every penny.

On Fri, May 27, 2016 at 6:03 PM, Elliott Sales de Andrade <
notifications@github.com> wrote:

> Weird, I don't know why I didn't receive a notification earlier. Anyway, I
> meant free as in "not taken", not "without charge".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/UofTCoders/Events/issues/52#issuecomment-222263152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AR1wJFdyxLX2WrLSHQC9AvP5KtMIbEGHks5qF2o7gaJpZM4IaeN7>
> .
>



-- 
Nattha Wannissorn
PhD Student
Department of Molecular Genetics
University of Toronto & Donnelly Centre
Laboratory of Dr. Andrew Fraser
160 College St
Toronto ON
M5S3E1
