### ISSUE TITLE
Intro to SQL - June 16

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#53]
This tutorial will go over the basics of how to use SQL to work with databases to store, query and manipulate your data.

**Where**: MP408
**When**: June 16, 2016, 6:10pm

More information to come.

**Comment by pipitone** [comment]
More specifically, I'll introduce you to the basics of SQL -- the language for interacting with a database -- and relate it to familiar R and Python operations. After a quick tour, we can talk about how you might (or might not) want to use a database to manage your study data.

**You'll need:** Either Firefox and the [SQLite Manager plugin](https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/), or [sqlite3](https://www.sqlite.org/download.html) to use from the command-line.

**Comment by mbonsma** [comment]
Today's event will be live-streamed [here](http://youtu.be/pQJjoQoOqRA).
