### ISSUE TITLE
July 14 - Debugging in Python

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#56]
Learn how to debug in python using the debugging tool in most IDE's. 

**Where**: MP408
**When**: July 14th, 6:10pm-7pm
**Preparation**: Come with Python installed on your computer as well as an IDE. If you're using [Anaconda](https://www.continuum.io/downloads), it comes with Spyder, an IDE. (Anaconda is a great way to get Python with a bunch of useful packages at the same time!)

The lesson material is [here](https://github.com/UofTCoders/studyGroup/pull/148/files), and includes some functions that will be used.

**Comment by mbonsma** [comment]
Tonight's session will be live-streamed [here](http://youtu.be/OFOn2ZKuzek)!
