### ISSUE TITLE
July 21 - Intro to ggplot2 in R

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#57]
A brief introduction to the ggplot2 package and making simple graphs in R.

**When:** July 21, 2016, 6:10-7:00pm
**Where:** MP 408 
**Preparation:**

Install:

R
RStudio
Because internet is sporatic in MP408, please come to the session with dplyr, tidyr, and ggplot2 packages installed either by using the RStudio "Tools->Install packages" option or by typing these commands into the R console:

install.packages('dplyr')
install.packages('tidyr')
install.packages('ggplot2')

**Comment by mbonsma** [comment]
Watch the recording [here](https://www.youtube.com/watch?v=Z0gf2M1sK6o)!

**Comment by mbonsma** [comment]
Below is the code from the lesson, and [this link](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/ggplot2/lesson.md) points to the other ggplot2 lesson done by Sarah.

```
installed.packages("ggplot2")

library(ggplot2)

# 1. dataframe
# 2. aesthetics: how the data are displayed (colour size)
# 3. geoms: geometric objects like points, lines, shapes

g <- ggplot(data = mpg, aes(displ, hwy)) +
  geom_point(aes(color=drv), size = 1) +
  geom_smooth(method="lm", size = 1, se = FALSE) +
  theme_bw(base_family = "Times") +
  labs(title= "My Graph :D", x= "Engine Displacement (L)", y = "Highway miles per Gallon") +
  facet_grid(drv ~ .)

library(reshape2)
library(dplyr)


mtcars %>%
  select(c(1,3,4,5,6,7)) %>%
  cor() %>% 
  round(2) %>% 
  melt() %>%
  ggplot(aes(x=Var1,y=Var2, fill=value)) +
  geom_tile()

t <- select(mtcars, c(1,3,4,5,6,7))
r <- cor(t)
q <- round(r, 2)
w <- melt(q)
ggplot(w, aes(x=Var1,y=Var2, fill=value)) +
  geom_tile()
```
