### ISSUE TITLE
 Lightning Demos: Data Visualization + Pub Night - Aug 4

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#58]
See how others make use of different tools and packages to visualize their data through some lightning demos. 

**Where**: MP408
**When**: Thursday, August 4th, 6:10pm to 7pm

**Comment by linamnt** [comment]
We will also be having a pub social at the GSU Pub afterwards  (7pm) for those interested!

**Comment by QuLogic** [comment]
@linamnt Don't forget to add this to the front page.

**Comment by QuLogic** [comment]
Thanks to everyone who presented something. We had lightning talks about:
* [plot.ly](https://plot.ly/) and [bokeh](http://bokeh.pydata.org/en/latest/) (in passing)
 * [UofT WebSurvey (clicker replacement)](http://uoft.ws) (I don't have a link to the slides though, so this link doesn't show much.)
 * [d3.js](https://d3js.org/)
 * [matplotlib styles](http://matplotlib.org/users/style_sheets.html)
 * [tqdm](https://pypi.python.org/pypi/tqdm)
 * [missingno](https://github.com/ResidentMario/missingno)

Please leave a note if I left something out.
