### ISSUE TITLE
Coworking Session - Aug 11

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#59]
Work on a project of yours, help others or discuss problems you're experiencing with your code. Beginners welcome, bring your friends!

**Where**: MP408
**When**: Thursday, August 11 6pm to 7:30pm

**Comment by drashti4** [comment]
Hey!I'm interested.From where can I know agenda and how can I attend this?Any link?

**Comment by linamnt** [comment]
Hi Drashti,

For coworking sessions, there isn't generally any preset agenda. People who
attend will usually discuss what they're working on and possibly ask for
suggestions from the others or people will bring something to work on in
that time. No registration is necessary, just show up at Mclennan Physical
Laboratories
<https://www.google.ca/maps/place/McLennan+Physical+Laboratories,+Toronto,+ON+M5S/@43.6608787,-79.3984443,17z/data=%213m1%214b1%214m2%213m1%211s0x882b34bf43351f69:0x36b6dd5f4f4ae5be>
room
408 starting from 6pm.

Thanks!
