### ISSUE TITLE
Plotting with Python and Matplotlib

### ISSUE THREAD

**Issue by ricardoharripaul** [UofTCoders/Events#6]
This session will be a beginner's guide to matplotlib and basic plotting in python.  We will also cover animations from your graphs for particle trajectory and reproducible figures for plots.

**Date: Thursday August 6th, 2015, 6 pm - 7 pm**
**Place: [McLennan Physics building](https://www.google.ca/maps?q=mclennan+physical+laboratories&ion=1&espv=2&bav=on.2,or.r_cp.&bvm=bv.99261572,d.aWw&biw=1517&bih=714&um=1&ie=UTF-8&sa=X&ved=0CAYQ_AUoAWoVChMIjsSwkuePxwIVxDqSCh0SbwDk) Rm. 408**

For those who do not have Python and Matplotlib installed please install these dependencies.  Also if you want to do particle trajectory animation make sure you have an MPEG encoder installed.  I use linux so my encoder is ffmpeg.  This can be used with Windows and here are several alternatives for Mac (http://alternativeto.net/software/ffmpeg/?platform=mac).

**Comment by mbonsma** [comment]
Room 408 is in the Burton Tower, 4th floor: if you're coming in from St. George Street, go in the main doors and turn left, then right (through three sets of doors) until you hit the elevators. From Huron Street, turn right, then right again until you hit the elevators. From Russell Street, go in the doors and turn left, and you're right at the elevators.

**Comment by ricardoharripaul** [comment]
Hi,

I pushed my python code to the Github as per the instructions but I cannot
view any of the files on the UofTCoders group Github.

**Comment by QuLogic** [comment]
@ricardoharripaul Your changes are in your fork. You need to open a PR to request merges into the main repo.

**Comment by ricardoharripaul** [comment]
So I opened a public repository and I am trying to copy one repo to
another.  Having some trouble.

ricardo@ricardo-G750JW[studyGroup] git push -u origin master          [
2:18PM]
Username for 'https://github.com': ricardoharripaul
Password for 'https://ricardoharripaul@github.com':
error: src refspec master does not match any.
error: failed to push some refs to '
https://github.com/ricardoharripaul/studyGroup.git'

Any ideas?

**Comment by ricardoharripaul** [comment]
I think it is up on  a public repo.  Can you check please?

https://github.com/ricardoharripaul/PlottingwithPython

**Comment by QuLogic** [comment]
It is in your repo. You need to [open a pull request](https://help.github.com/articles/using-pull-requests/) now.

**Comment by QuLogic** [comment]
(Make sure to use UofTCoders as the base fork.)

**Comment by lwjohnst86** [comment]
Probably is way too late, but at least for next time. I've written up a how to on contributing on our wiki: https://github.com/UofTCoders/studyGroup/wiki/Contributing-a-lesson check it there
