### ISSUE TITLE
Large Datasets in Python | August 25

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#60]
A brief overview about how to deal with large datasets in Python with respect to storing, reading in and working with the data.

**Where**: MP408
**When**: Aug 25th, 2016 6:10pm-7:00pm
**What to bring**: A laptop with Python (via [Anaconda](https://www.continuum.io/downloads)) installed. An internet connection is helpful!

**Comment by josephdviviano** [comment]
Hey, how large is large? Trying to figure out if this is relevant to me.

**Comment by linamnt** [comment]
Hi @josephdviviano,

Wei (@gattacagithub ) will be presenting this topic and indicated that people working on the GB+ scale might run into unique issues that you wouldn't run into with large but say, only MB level, datasets which is mainly what will be presented in this lecture. 

So while some principles should scale, for specific issues that arise due to really really large data, I would say that's beyond the scope of this lesson. Hope that helps!

**Comment by josephdviviano** [comment]
Yes very helpful, thanks!

**Comment by gattacagithub** [comment]
Hey,

Thanks Lina for the explanation! And I'd like to add that if there's something in particular that you have in mind, please let me know.

**Comment by mbonsma** [comment]
This event will be live-streamed [here](http://youtu.be/ppRSG2jkDA8)!

**Comment by QuLogic** [comment]
Can we please have the lesson posted ASAP? The live-stream was not working this week.

**Comment by gattacagithub** [comment]
Sure I'm working on that. You should be able to see it in a few minutes.

**Comment by gattacagithub** [comment]
Hey the lesson is now uploaded!
https://github.com/gattacagithub/studyGroup/tree/gh-pages/lessons/LargeDatasetPython

**Comment by lwjohnst86** [comment]
Thanks Wei! Could you submit a pull request of the lesson to the uoftcoders studygroup repo? 

On 25 August, 2016 10:17:27 PM EDT, Wei Zhan <notifications@github.com> wrote:
>Hey the lesson is now uploaded!
>https://github.com/gattacagithub/studyGroup/tree/gh-pages/lessons/LargeDatasetPython
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/UofTCoders/Events/issues/60#issuecomment-242606737

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gattacagithub** [comment]
Hey it's now submitted!
