### ISSUE TITLE
Class Structure in Python | August 18

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#61]
Here we will touch on the concepts of object-oriented programming and dive into creating and using classes in Python.

**When:** August 18, 2016, 6:10pm - 7pm
**Where**: MP 408
**Preparation:**  

Python 2.7, or 3.4+ installed. If you're using Anaconda, it comes with Jupyter Notebook which you can use to follow along as well.

**Comment by mbonsma** [comment]
Watch the live stream / recording [here](http://youtu.be/wqfQEL8YiQg)!
