### ISSUE TITLE
Intro Python - Sep 14

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#64]
A brief introduction to Python programming. No experience is necessary to attend this lesson.

**Where**: MP408
**When**: **Wednesday, Sep 14, 6pm-7pm**
**What to bring**: A laptop with Python 2 or 3 installed. We highly recommend installing Python through an [Anaconda](https://www.continuum.io/downloads) distribution which comes with many useful packages for scientific computing.

**Comment by linamnt** [comment]
Correction, **Wednesday** Sep 14 6-7pm.

**Comment by QuLogic** [comment]
No live stream today?

**Comment by linamnt** [comment]
Yeah unfortunately my laptop wouldn't connect :(
