### ISSUE TITLE
Making Packages in R - October 12

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#68]
Learn about how you can package your code for reuse in R. 

**Where**: MP408
**When**: Wednesday, October 12, 6:10pm
**What to bring**: A laptop with R and RStudio installed. We will be using the package `devtools`.

**Comment by lwjohnst86** [comment]
Please make sure that these packages are installed before coming to the session: `install.packages(c('devtools', 'roxygen2', 'rmarkdown')`

**Comment by QuLogic** [comment]
The stream is [available here](https://youtu.be/am2OtzYIHFw).
