### ISSUE TITLE
Themed coworking session: plotting in Python and/or R

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/Events#7]
We've had two code-alongs on graphics/plotting, [one in R](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/Shiny), and [one in Python](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/PlottinginPythonwithMatplotlib). Let's meet for an informal discussion on what plotting methods people use or want to use day-to-day. Have you applied something from one of these sessions? Do you use any neat tricks that weren't covered, or were covered that you can show in action? What kinds of plots do you make in either Python or R? Do you have any questions (about anything)? Even if you didn't go to either session (*cough* like me) or you've never plotted in R or Python, you're most welcome to participate. Feel free to also suggest ideas for future plotting-related code-alongs or lightning demos. 

**When: August 13, 2015, 6pm - 7:30 ish pm**
**Where: [McLennan Physics building](https://www.google.ca/maps?q=mclennan+physical+laboratories&ion=1&espv=2&bav=on.2,or.r_cp.&bvm=bv.99261572,d.aWw&biw=1517&bih=714&um=1&ie=UTF-8&sa=X&ved=0CAYQ_AUoAWoVChMIjsSwkuePxwIVxDqSCh0SbwDk) Rm. 408**
**Preparation:** You may want to bring your laptop so you can point to images or code on your screen if desired.

**Directions to MP408:**
Room 408 is in the Burton Tower, 4th floor.
From St. George Street: go in the main doors and turn left, then right (through three sets of doors) until you hit the elevators. 
From Huron Street: go in the doors and turn right, then right again (through three sets of doors) until you hit the elevators. 
From Russell Street: go in the doors and turn left (one set of doors), you'll be right at the elevators.

**Comment by mbonsma** [comment]
Hope to see you all tonight - there will be snacks!

**Comment by lwjohnst86** [comment]
For those interested in what we talked about, here are the links to the (unreliable) p-value:

Youtube of p-value dance:
https://www.youtube.com/watch?v=ez4DgdurRPg&feature=youtu.be

An interactive plot showing the p-value + confidence interval dance (which btw uses D3):
http://rpsychologist.com/d3/CI/

Or for the reliability of randomized clinical trials (interactive):
http://www.economist.com/blogs/graphicdetail/2015/07/daily-chart-other-placebo-effect

**Comment by mbonsma** [comment]
Along the same lines, another good read about p-values and the significance of results: http://fivethirtyeight.com/features/science-isnt-broken/?ex_cid=story-twitter

**Comment by aerler** [comment]
That's a good read, I agree. The article I mentioned last time is also referenced there; it is the one by John Ioannidis: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1182327/

**Comment by QuLogic** [comment]
Here's the talk on the updated colour map in matplotlib (but also a good bit of colour theory): https://www.youtube.com/watch?v=xAoljeRJ3lU
