### ISSUE TITLE
Intro to Databases and SQL - November 2

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#70]
Learn about databases and how we can use SQL to interact with them to store, access and query our data. 

**Where**: MP408
**When**: Wednesday, November 2nd, 6:10pm
**What to bring**: More information to come

**Comment by linamnt** [comment]
## Requirements

To follow along with the lesson, you will need a several R and Python libraries. If you don't have R, Python, and sqlite3, see Basic System Requirements. For Python, consider creating a virtualenv for your workspace.

Now you are ready to install the required R and Python libraries. Inspect and run the following files:

pip install -r requirements/requirements.txt
R --no-save < requirements/requirements.R
You can also automatically install requirements on Mac and Linux:

make requirements

## Basic System Requirements

This lesson makes use of the following:

Python (Jupyter)
R (IRkernel for Jupyter)
sqlite3
Mac

MacOS already has Python and probably sqlite3 as well. You need R.

brew install R
Linux

You need R. Try apt, yum, or whatever:

apt-get install r-base
yum install R
You may need to install sqlite3. You can test by running:

which sqlite3
If it returns nothing, then it is not currently installed. Try apt, yum, or whatever:

apt-get install sqlite3 libsqlite3-dev
yum install sqlite sqlite-devel
Windows

You need Python, R, sqlite3, and maybe other things like a C compiler. These links will get you started:

https://cran.r-project.org/bin/windows/base/
https://www.rstudio.com/products/rstudio/download/
https://www.python.org/downloads/windows/
https://sqlite.org/download.html

**Comment by dmgroppe** [comment]
Which building is "MP408" in?

**Comment by QuLogic** [comment]
McLennan Physical Labs. 60 St. George St.

**Comment by lwjohnst86** [comment]
Video is live-streamed [here](https://www.youtube.com/watch?v=zs9Be1PVi4k)
