### ISSUE TITLE
Careers outside academia discussion - November 16

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#72]
Come join our open discussion on careers outside academia. All are welcome and bring a friend. 

**Where**: MP408
**When**: Wednesday, November 16th, 6:10pm
**What to bring**: N/A

**Comment by mbonsma** [comment]
[Here](https://github.com/UofTCoders/studyGroup/pull/180/files) are the notes from this discussion!

**Comment by linamnt** [comment]
https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/careers_outside_academia/lesson.md 
for future reference

**Comment by mbonsma** [comment]
Link was changed, updated link here: https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/misc/careers-outside-academia/lesson.md
