### ISSUE TITLE
Pandoc and Markdown - November 30

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#73]
A brief introduction to how you can use Pandoc and Markdown to convert between filetypes when preparing documents and more. 

**Where**: MP408
**When**: Wednesday, November 30th, 6:10pm
**What to bring**: More information to come.

**Comment by jdpigeon** [comment]
### Intro to Pandoc

Do you enjoy the spartan, academic aesthetic of LaTeX documents but not have the time to learn it's unforgiving syntax? Does writing HTML documents by hand remind you too much of your difficult primary school days? Do you enjoy automating difficult things? Then Pandoc might be for you. 

Pandoc is a command line tool (you're comfortable with those, right?) that you can use to automatically convert files from markup format to another. With Pandoc, you can write using something easy like Markdown, Microsoft Word, or LibreOffice, and convert it something hard like:
- HTML
- Ebook formats
- LaTeX
- PDF
- and many others

### Intro to Markdown

Markdown is probably the best way to write things for Pandoc. If you haven't heard of it, it's a lightweight, shortdown version of HTML that a lot of people on the internet use to write stuff. It's like writing in plain text, but you have access to important symbols `* ~ - #` that let you insert HTML-style formatting easily. The veritable bible of Markdown is [Daring Fireball.](https://daringfireball.net/projects/markdown/)

### Getting Started (what to install before class)

- Install [Pandoc](http://pandoc.org/installing.html)
- Install LaTeX: [TeXLive (Linux)](http://www.tug.org/texlive/), [MacTeX (Mac)](http://www.tug.org/mactex/), [MikTeX (Windows)](https://miktex.org/)
- Install XeTex?

Whether you're doing something like `sudo apt-get pandoc && apt-get texlive` or `brew install pandoc && brew cask install mactex`, if you can run `pandoc -v` and `pdflatex -v` in a terminal, you're good to go.

**Comment by mbonsma** [comment]
The live stream is [here](https://www.youtube.com/watch?v=Szi3wxr5IHA)!

**Comment by mbonsma** [comment]
To follow along, download the sample material [here](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/pandoc_markdown).
