### ISSUE TITLE
Web Design with Jekyll/Github Pages - November 23

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#74]
Github Pages allow users to host websites for free from Github repositories using Jekyll and plain HTML content. No prior experience with GitHub, HTML or Jekyll is necessary, all are welcome. We will be trying out a few different tools so make sure to check the installation instructions.

**When:** Wednesday, November 23rd, 6:10pm
**Where:** MP 408 
**What to bring:** Computer, charged if possible, with a GitHub account, Git installed and if possible Jekyll installed too (instructions below)

GitHub Account

If you don't have one go to https://github.com/join

Git

[Installation instructions](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) and [download links](https://git-scm.com/downloads) can be found on the Git site.

Jekyll

[Installation instructions](https://jekyllrb.com/docs/installation/) for Jekyll can be found on the Jekyll site

Unfortunately Windows is not officially supported, however there are instructions for Jekyll on Windows.

**Comment by mbonsma** [comment]
If you're using Windows, try these instructions for Ruby/Jekyll: https://labs.sverrirs.com/jekyll/

**Comment by QuLogic** [comment]
Live stream is [here](https://youtu.be/XeJup9GXxNU) (sorry for the late post.)
