### ISSUE TITLE
Cartography and Mapping in Python - October 5

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#76]
We will be having an overview of cartography and mapping methods and tools you can use in Python.

**Where**: MP408
**When**: Wednesday, October 5th, 6:10pm
**What to bring**: Install Cartopy:
```
$ conda install -c conda-forge cartopy
```
Also, to pre-cache the data, download and run [this script](https://gist.github.com/QuLogic/bf35753c7df979d97f25e58290985a48) after installing Cartopy and download the zip file as well. It is not strictly necessary, but useful to avoid an connectivity issues in MP408.

**Comment by QuLogic** [comment]
Live stream will hopefully be available here: http://youtu.be/ymuGD65P2_s

**Comment by QuLogic** [comment]
Apologies to anyone watching this at home, but there were some technical issues causing a disconnection part way through.

Please [view the entire lesson here](https://uoftcoders.github.io/studyGroup/lessons/cartography/lesson/). The stream was disconnected at the Features section, around the discussion of scale.
