### ISSUE TITLE
Intro to Python - Jan 18th

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#80]
The very basics of the programming language Python with a beginner-friendly code-along.

**Where:** MP408
**When:**  Wednesday, January 18th, 6:10pm
**Preparation:** Bring a laptop computer, and download Python (preferably 3, but 2 is also fine) using [Anaconda](https://continuum.io/downloads) which includes Python, IPython, NumPy, and many other useful packages. We highly recommend using Anaconda if you do not yet have Python. 

If you're on Mac or Linux, you probably already have Python installed. 

**Edit:** here are some [instructions for installing Anaconda](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md) courtesy of @joelostblom. 

Follow along with the lesson material [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/intro/IntroPython-MB.ipynb).

**Comment by joelostblom** [comment]
[Anaconda installation instructions!](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md) =)

**Comment by mbonsma** [comment]
The live stream is [here](https://www.youtube.com/watch?v=5OQ5Gx1OUEI)!
