### ISSUE TITLE
Collaborating with GitHub - Feb 22

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#83]
Git and Github are tools not only for version control of your own code, but are widely used for collaborative team coding! Learn more about how you can use Git collaboratively on a project, the genereal workflow as well as details about the step-by-step process.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, February 22nd, 6:10pm - 7:30pm
**Instructor**: @sjeblee
**What to bring**: Bring a laptop with Git installed (see instructions below) and make an account on [GitHub](https://github.com/join?source=header-home). It's free! 
### Git

Installation instructions for Git can be found on the [Git download site](https://git-scm.com/book/en/Getting-Started-Installing-Git)
- On Windows: Download the `.exe` file from this
  [Github link](https://msysgit.github.io) and run it.
- On Mac: To use the graphical Git installer, download from this
  [SourceForge link](https://sourceforge.net/projects/git-osx-installer/)
- On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by QuLogic** [comment]
Video stream was [here](https://www.youtube.com/watch?v=vrftiQcqIYM).
