### ISSUE TITLE
Intro to ggplot2 in R - February 15

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#84]
ggplot2 is a great and versatile package in R for plotting your data. We will do a code-a-long showing you different types of plots and how to customize them.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, February 15, 6:10pm
**Instructor**: @lcoome 
**What to bring**:  A laptop with [R](https://www.r-project.org/) and [RStudio](https://www.rstudio.com/products/rstudio/download/) installed.

Then run the following:

`install.packages('ggplot2')`
`install.packages('plotly')`

**Comment by QuLogic** [comment]
For future reference, video stream was [here](https://www.youtube.com/watch?v=jQVKQcbu92o).

**Comment by lcoome** [comment]
That is last year's video stream. Mine is here: https://www.youtube.com/watch?v=EKkpflv-O_k


Sarah and I sound alike I guess!

________________________________

**Comment by QuLogic** [comment]
Weird, did @linamnt re-upload your video? I could have sworn the videos from the other channel were uploaded after you presented your lesson.

I probably should have listened to them first...

**Comment by lcoome** [comment]
Haha we sound alike anyways...

________________________________
