### ISSUE TITLE
Lightning Demos: Data Visualization - March 8

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#87]
Give a short demo on a visualization you've made, a tool you can use or a package for this. 

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, March 8th, 6:10pm
**Instructor**: NA
**What to bring**: Your laptop with a brief demo (no more than 5-10 min!) if you're presenting. Otherwise, just yourself!

**Comment by joelostblom** [comment]
I can give an overview on Bokeh for this one.

**Comment by mbonsma** [comment]
I can do a demo of making animations with matplotlib.

**Comment by aays** [comment]
Here's Yihui Xie's pyramid pie chart code!

`par(mar = c(0,1,0,1))

pie(
  c(280,60,20),
  c('Sky', 'Sunny side of the pyramid', 'Shady side of the pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50,
  border = NA
) `

**Comment by joelostblom** [comment]
Here is the talk I mentioned from Hans Rosling - [The best stats you have ever seen](https://www.youtube.com/watch?v=hVimVzgtD6w&list=PLO_OaQZ3Gmd7NYH4lRxIfMyd9FosWsp6-). Beyond creative visualizations, this talk demonstrates how to engage your audience through exemplary scientific communication skills. The first ten minutes are thoroughly entertaining while dealing with heavy topics. Rosling gets into some specifics about data openness and accessibility around the 15 min mark.

Note that this talk is from over ten years ago, when there were not many (if any) sophisticated presentation tools around. If I recall correctly, Rosling's son and his girlfriend initially custom built these presentations in flash. They later founded the gapminder foundation and made their tools freely available for public use, enabling people to easily browse through the world's data. Google later acquired the software, which is [now available as an online gadget](http://www.gapminder.org/tools/#_state_marker_color_scaleType=ordinal;&size_slash__label_which=_slash__default&use=constant;;;&chart-type=bubbles).
