### ISSUE TITLE
Intro to SQL - March 15

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#88]
Learn about SQL and databases, and how you can use them to store, access and query your data.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, March 15th, 6:10pm
**Instructor**: Brian Sutherland
**What to bring**: TBD

**Comment by ProgrammingSnoopy** [comment]
Hi, do you know how long this workshop will be running for? Thank you!

**Comment by linamnt** [comment]
Hi @ProgrammingSnoopy it will be from 6:10-7pm

**Comment by ProgrammingSnoopy** [comment]
@linamnt Thank you!

**Comment by bksutherland** [comment]
Here's a good cheat sheet to print out, of all things MySQL and the main queries we learned, on one page.  I'm not the author; it says the doc is free, I'm going to assume free to redistribute (somebody correct me if that's not the case).
https://bmc.med.utoronto.ca/bmcwiki/lib/exe/fetch.php/technologies:mysql_cheat_sheet.pdf

Practice examples:

What were the five most frequently played songs?

SELECT * FROM `jack_titles` ORDER BY frequency DESC LIMIT 5

What were the five most frequently played songs by the artist/band Rush?

SELECT * FROM `jack_titles`  WHERE artist = 'Rush' ORDER BY frequency DESC LIMIT 5

How many songs were played in `2005`

SELECT COUNT(*) AS totalsongs FROM `jack_playlist` WHERE dateandtime LIKE '%2005%'

How many distinct artists were played in 2005?

SELECT COUNT(DISTINCT(artist)) AS total artists FROM `jack_playlist` WHERE dateandtime LIKE '%2005%'

Installing a LAMP server on OSX 10.12.3 (Sierra)
https://coolestguidesontheplanet.com/get-apache-mysql-php-and-phpmyadmin-working-on-macos-sierra/

On Ubuntu (raspberry pi is a great cheap and convenient implementation)
https://help.ubuntu.com/community/ApacheMySQLPHP

On Windows (maybe you prefer Perl)
https://www.apachefriends.org/download.html

Could use python to talk to MySQL if you prefer, or Node.js (server javascript), they both work very well.

PostGreSQL is a more full-featured open source SQL server, but harder to use.  It has for example, a command called 'vacuum'.

PhpMyAdmin db manager
https://www.phpmyadmin.net/

Installation instructions
https://docs.phpmyadmin.net/en/latest/

On entity-relationships
https://bmc.med.utoronto.ca/bmcwiki/doku.php/technology:web_applications:entity-relationship

Wikipedia
https://upload.wikimedia.org/wikipedia/commons/2/2c/Mediawiki_dbschema.svg
