### ISSUE TITLE
Intermediate Topics in R - March 29

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#90]
More intermediate level topics in R. More information to follow

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, March 29th, 6:10pm
**Instructor**: @lwjohnst86 
**What to bring**: 
A laptop with R and RStudio installed. 
Instructions:
https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md
Have the packages `forcats` and `stringr` installed

**Comment by OrdiNeu** [comment]
Both this and #89 are assigned the same time/place. Are they going to be in the same room?

**Comment by linamnt** [comment]
Hi @OrdiNeu Sorry my mistake, this will take place **Wednesday March 29th.**
Thanks!
