### ISSUE TITLE
Intermediate Topics in Python - April 5

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#91]
Intermediate topics in Python. More information to follow.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, April 5th, 6:10pm
**Instructor**: Ahmed Hasan
**What to bring**: A laptop with Python 3+ installed. We recommend the[ Anaconda distribution. ](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r-python-conda-setup.md)

**Comment by mbonsma** [comment]
https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/intermediate/scores.txt

**Comment by mbonsma** [comment]
Live stream is [here](https://www.youtube.com/watch?v=33Pgx0DlNmo)!
