### ISSUE TITLE
Lightning Demos: Academic Workflows -  April 12

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#92]
What tools and programs do you use to analyze, visualize and communicate your data? Come show us your academic workflow and see how others work as well.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, April 12th, 6:10pm
**Instructor**: NA

**Comment by lwjohnst86** [comment]
I can present one demo!

**Comment by joelostblom** [comment]
I can introduce Zsh and tmux for about 4-5 min each

**Comment by linamnt** [comment]
I will briefly show how I use Atom + Hydrogen (like jupyter notebook but in Atom) for my coding.

**Comment by mbonsma** [comment]
Here's the [Google Hangout link](https://hangouts.google.com/hangouts/_/vpzcldkbt5gaxc5s2red23jtrqe) - if you're presenting, join the hangout to be live-streamed!

**Comment by mbonsma** [comment]
A few other tools that came up in discussion, mostly to do with task lists:
* [Zathura](https://pwmt.org/projects/zathura/)
* [Todo.txt](http://todotxt.com/)
* [Git done](https://github.com/staltz/git-done)
* [Task Warrior](https://taskwarrior.org/)
* [Hub](https://hub.github.com/)
* [ghi](https://github.com/stephencelis/ghi)
* Vim.csv
* [Org mode](http://orgmode.org/)
* [Activate power mode](https://atom.io/packages/activate-power-mode) in Atom
