### ISSUE TITLE
Lightning Demos: Working with Very Large Datasets - May 10 

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#98]
Do you know a tool or package for working with **very** large datasets (on the order or GB/TB)? Or want to learn more? Come see our quick (10 min or less) demos on this topic.

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](https://www.openstreetmap.org/way/14748316)
**When**: Wednesday May 10th, 6:10pm-7pm
**Instructor**: NA
**What to bring**: If you're doing a demo, please bring a laptop with your presentation or demo prepared.

**Comment by mbonsma** [comment]
The live stream recording is [here](https://www.youtube.com/watch?v=3xKRdJxIQk0). We talked about [Dask](http://dask.pydata.org/en/latest/), [git lfs](https://git-lfs.github.com/), [git-annex](https://git-annex.branchable.com/), and handy bash commands for working with large files: `less`, `cat`, and `split`. Thanks @QuLogic and @aays for the demos!
